include(
        ":app",
        ":playstore",
        ":lib:applog",
        ":lib:compose",
        ":lib:graphics",
        ":lib:framework",
        ":lib:ktx",
        ":lib:colorpicker",
        ":lib:permissions"
)