// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

public interface AndroidBuildProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.AndroidBuildProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string product = 2;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>optional string product = 2;</code>
   * @return The product.
   */
  java.lang.String getProduct();
  /**
   * <code>optional string product = 2;</code>
   * @return The bytes for product.
   */
  com.google.protobuf.ByteString
      getProductBytes();

  /**
   * <code>optional string carrier = 3;</code>
   * @return Whether the carrier field is set.
   */
  boolean hasCarrier();
  /**
   * <code>optional string carrier = 3;</code>
   * @return The carrier.
   */
  java.lang.String getCarrier();
  /**
   * <code>optional string carrier = 3;</code>
   * @return The bytes for carrier.
   */
  com.google.protobuf.ByteString
      getCarrierBytes();

  /**
   * <code>optional string radio = 4;</code>
   * @return Whether the radio field is set.
   */
  boolean hasRadio();
  /**
   * <code>optional string radio = 4;</code>
   * @return The radio.
   */
  java.lang.String getRadio();
  /**
   * <code>optional string radio = 4;</code>
   * @return The bytes for radio.
   */
  com.google.protobuf.ByteString
      getRadioBytes();

  /**
   * <code>optional string bootloader = 5;</code>
   * @return Whether the bootloader field is set.
   */
  boolean hasBootloader();
  /**
   * <code>optional string bootloader = 5;</code>
   * @return The bootloader.
   */
  java.lang.String getBootloader();
  /**
   * <code>optional string bootloader = 5;</code>
   * @return The bytes for bootloader.
   */
  com.google.protobuf.ByteString
      getBootloaderBytes();

  /**
   * <code>optional string client = 6;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>optional string client = 6;</code>
   * @return The client.
   */
  java.lang.String getClient();
  /**
   * <code>optional string client = 6;</code>
   * @return The bytes for client.
   */
  com.google.protobuf.ByteString
      getClientBytes();

  /**
   * <code>optional int64 timestamp = 7;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>optional int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>optional int32 googleServices = 8;</code>
   * @return Whether the googleServices field is set.
   */
  boolean hasGoogleServices();
  /**
   * <code>optional int32 googleServices = 8;</code>
   * @return The googleServices.
   */
  int getGoogleServices();

  /**
   * <code>optional string device = 9;</code>
   * @return Whether the device field is set.
   */
  boolean hasDevice();
  /**
   * <code>optional string device = 9;</code>
   * @return The device.
   */
  java.lang.String getDevice();
  /**
   * <code>optional string device = 9;</code>
   * @return The bytes for device.
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <code>optional int32 sdkVersion = 10;</code>
   * @return Whether the sdkVersion field is set.
   */
  boolean hasSdkVersion();
  /**
   * <code>optional int32 sdkVersion = 10;</code>
   * @return The sdkVersion.
   */
  int getSdkVersion();

  /**
   * <code>optional string model = 11;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>optional string model = 11;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 11;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>optional string manufacturer = 12;</code>
   * @return Whether the manufacturer field is set.
   */
  boolean hasManufacturer();
  /**
   * <code>optional string manufacturer = 12;</code>
   * @return The manufacturer.
   */
  java.lang.String getManufacturer();
  /**
   * <code>optional string manufacturer = 12;</code>
   * @return The bytes for manufacturer.
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>optional string buildProduct = 13;</code>
   * @return Whether the buildProduct field is set.
   */
  boolean hasBuildProduct();
  /**
   * <code>optional string buildProduct = 13;</code>
   * @return The buildProduct.
   */
  java.lang.String getBuildProduct();
  /**
   * <code>optional string buildProduct = 13;</code>
   * @return The bytes for buildProduct.
   */
  com.google.protobuf.ByteString
      getBuildProductBytes();

  /**
   * <code>optional bool otaInstalled = 14;</code>
   * @return Whether the otaInstalled field is set.
   */
  boolean hasOtaInstalled();
  /**
   * <code>optional bool otaInstalled = 14;</code>
   * @return The otaInstalled.
   */
  boolean getOtaInstalled();
}
