// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

public interface AndroidCheckinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.AndroidCheckinRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string imei = 1;</code>
   * @return Whether the imei field is set.
   */
  boolean hasImei();
  /**
   * <code>optional string imei = 1;</code>
   * @return The imei.
   */
  java.lang.String getImei();
  /**
   * <code>optional string imei = 1;</code>
   * @return The bytes for imei.
   */
  com.google.protobuf.ByteString
      getImeiBytes();

  /**
   * <code>optional int64 id = 2 [default = 0];</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int64 id = 2 [default = 0];</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional string digest = 3;</code>
   * @return Whether the digest field is set.
   */
  boolean hasDigest();
  /**
   * <code>optional string digest = 3;</code>
   * @return The digest.
   */
  java.lang.String getDigest();
  /**
   * <code>optional string digest = 3;</code>
   * @return The bytes for digest.
   */
  com.google.protobuf.ByteString
      getDigestBytes();

  /**
   * <code>optional .finsky.protos.AndroidCheckinProto checkin = 4;</code>
   * @return Whether the checkin field is set.
   */
  boolean hasCheckin();
  /**
   * <code>optional .finsky.protos.AndroidCheckinProto checkin = 4;</code>
   * @return The checkin.
   */
  finsky.protos.AndroidCheckinProto getCheckin();

  /**
   * <code>optional string desiredBuild = 5;</code>
   * @return Whether the desiredBuild field is set.
   */
  boolean hasDesiredBuild();
  /**
   * <code>optional string desiredBuild = 5;</code>
   * @return The desiredBuild.
   */
  java.lang.String getDesiredBuild();
  /**
   * <code>optional string desiredBuild = 5;</code>
   * @return The bytes for desiredBuild.
   */
  com.google.protobuf.ByteString
      getDesiredBuildBytes();

  /**
   * <code>optional string locale = 6;</code>
   * @return Whether the locale field is set.
   */
  boolean hasLocale();
  /**
   * <code>optional string locale = 6;</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <code>optional string locale = 6;</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();

  /**
   * <code>optional int64 loggingId = 7;</code>
   * @return Whether the loggingId field is set.
   */
  boolean hasLoggingId();
  /**
   * <code>optional int64 loggingId = 7;</code>
   * @return The loggingId.
   */
  long getLoggingId();

  /**
   * <code>optional string marketCheckin = 8;</code>
   * @return Whether the marketCheckin field is set.
   */
  boolean hasMarketCheckin();
  /**
   * <code>optional string marketCheckin = 8;</code>
   * @return The marketCheckin.
   */
  java.lang.String getMarketCheckin();
  /**
   * <code>optional string marketCheckin = 8;</code>
   * @return The bytes for marketCheckin.
   */
  com.google.protobuf.ByteString
      getMarketCheckinBytes();

  /**
   * <code>repeated string macAddr = 9;</code>
   * @return A list containing the macAddr.
   */
  java.util.List<java.lang.String>
      getMacAddrList();
  /**
   * <code>repeated string macAddr = 9;</code>
   * @return The count of macAddr.
   */
  int getMacAddrCount();
  /**
   * <code>repeated string macAddr = 9;</code>
   * @param index The index of the element to return.
   * @return The macAddr at the given index.
   */
  java.lang.String getMacAddr(int index);
  /**
   * <code>repeated string macAddr = 9;</code>
   * @param index The index of the element to return.
   * @return The macAddr at the given index.
   */
  com.google.protobuf.ByteString
      getMacAddrBytes(int index);

  /**
   * <code>optional string meid = 10;</code>
   * @return Whether the meid field is set.
   */
  boolean hasMeid();
  /**
   * <code>optional string meid = 10;</code>
   * @return The meid.
   */
  java.lang.String getMeid();
  /**
   * <code>optional string meid = 10;</code>
   * @return The bytes for meid.
   */
  com.google.protobuf.ByteString
      getMeidBytes();

  /**
   * <code>repeated string accountCookie = 11;</code>
   * @return A list containing the accountCookie.
   */
  java.util.List<java.lang.String>
      getAccountCookieList();
  /**
   * <code>repeated string accountCookie = 11;</code>
   * @return The count of accountCookie.
   */
  int getAccountCookieCount();
  /**
   * <code>repeated string accountCookie = 11;</code>
   * @param index The index of the element to return.
   * @return The accountCookie at the given index.
   */
  java.lang.String getAccountCookie(int index);
  /**
   * <code>repeated string accountCookie = 11;</code>
   * @param index The index of the element to return.
   * @return The accountCookie at the given index.
   */
  com.google.protobuf.ByteString
      getAccountCookieBytes(int index);

  /**
   * <code>optional string timeZone = 12;</code>
   * @return Whether the timeZone field is set.
   */
  boolean hasTimeZone();
  /**
   * <code>optional string timeZone = 12;</code>
   * @return The timeZone.
   */
  java.lang.String getTimeZone();
  /**
   * <code>optional string timeZone = 12;</code>
   * @return The bytes for timeZone.
   */
  com.google.protobuf.ByteString
      getTimeZoneBytes();

  /**
   * <code>optional fixed64 securityToken = 13;</code>
   * @return Whether the securityToken field is set.
   */
  boolean hasSecurityToken();
  /**
   * <code>optional fixed64 securityToken = 13;</code>
   * @return The securityToken.
   */
  long getSecurityToken();

  /**
   * <code>optional int32 version = 14;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>optional int32 version = 14;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>repeated string otaCert = 15;</code>
   * @return A list containing the otaCert.
   */
  java.util.List<java.lang.String>
      getOtaCertList();
  /**
   * <code>repeated string otaCert = 15;</code>
   * @return The count of otaCert.
   */
  int getOtaCertCount();
  /**
   * <code>repeated string otaCert = 15;</code>
   * @param index The index of the element to return.
   * @return The otaCert at the given index.
   */
  java.lang.String getOtaCert(int index);
  /**
   * <code>repeated string otaCert = 15;</code>
   * @param index The index of the element to return.
   * @return The otaCert at the given index.
   */
  com.google.protobuf.ByteString
      getOtaCertBytes(int index);

  /**
   * <code>optional string serialNumber = 16;</code>
   * @return Whether the serialNumber field is set.
   */
  boolean hasSerialNumber();
  /**
   * <code>optional string serialNumber = 16;</code>
   * @return The serialNumber.
   */
  java.lang.String getSerialNumber();
  /**
   * <code>optional string serialNumber = 16;</code>
   * @return The bytes for serialNumber.
   */
  com.google.protobuf.ByteString
      getSerialNumberBytes();

  /**
   * <code>optional string esn = 17;</code>
   * @return Whether the esn field is set.
   */
  boolean hasEsn();
  /**
   * <code>optional string esn = 17;</code>
   * @return The esn.
   */
  java.lang.String getEsn();
  /**
   * <code>optional string esn = 17;</code>
   * @return The bytes for esn.
   */
  com.google.protobuf.ByteString
      getEsnBytes();

  /**
   * <code>optional .finsky.protos.DeviceConfigurationProto deviceConfiguration = 18;</code>
   * @return Whether the deviceConfiguration field is set.
   */
  boolean hasDeviceConfiguration();
  /**
   * <code>optional .finsky.protos.DeviceConfigurationProto deviceConfiguration = 18;</code>
   * @return The deviceConfiguration.
   */
  finsky.protos.DeviceConfigurationProto getDeviceConfiguration();

  /**
   * <code>repeated string macAddrType = 19;</code>
   * @return A list containing the macAddrType.
   */
  java.util.List<java.lang.String>
      getMacAddrTypeList();
  /**
   * <code>repeated string macAddrType = 19;</code>
   * @return The count of macAddrType.
   */
  int getMacAddrTypeCount();
  /**
   * <code>repeated string macAddrType = 19;</code>
   * @param index The index of the element to return.
   * @return The macAddrType at the given index.
   */
  java.lang.String getMacAddrType(int index);
  /**
   * <code>repeated string macAddrType = 19;</code>
   * @param index The index of the element to return.
   * @return The macAddrType at the given index.
   */
  com.google.protobuf.ByteString
      getMacAddrTypeBytes(int index);

  /**
   * <code>optional int32 fragment = 20;</code>
   * @return Whether the fragment field is set.
   */
  boolean hasFragment();
  /**
   * <code>optional int32 fragment = 20;</code>
   * @return The fragment.
   */
  int getFragment();

  /**
   * <code>optional string userName = 21;</code>
   * @return Whether the userName field is set.
   */
  boolean hasUserName();
  /**
   * <code>optional string userName = 21;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>optional string userName = 21;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>optional int32 userSerialNumber = 22;</code>
   * @return Whether the userSerialNumber field is set.
   */
  boolean hasUserSerialNumber();
  /**
   * <code>optional int32 userSerialNumber = 22;</code>
   * @return The userSerialNumber.
   */
  int getUserSerialNumber();
}
