// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.AndroidCheckinProto}
 */
public  final class AndroidCheckinProto extends
    com.google.protobuf.GeneratedMessageLite<
        AndroidCheckinProto, AndroidCheckinProto.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.AndroidCheckinProto)
    AndroidCheckinProtoOrBuilder {
  private AndroidCheckinProto() {
    event_ = emptyProtobufList();
    stat_ = emptyProtobufList();
    requestedGroup_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    cellOperator_ = "";
    simOperator_ = "";
    roaming_ = "";
  }
  private int bitField0_;
  public static final int BUILD_FIELD_NUMBER = 1;
  private finsky.protos.AndroidBuildProto build_;
  /**
   * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
   */
  @java.lang.Override
  public boolean hasBuild() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
   */
  @java.lang.Override
  public finsky.protos.AndroidBuildProto getBuild() {
    return build_ == null ? finsky.protos.AndroidBuildProto.getDefaultInstance() : build_;
  }
  /**
   * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
   */
  private void setBuild(finsky.protos.AndroidBuildProto value) {
    value.getClass();
  build_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeBuild(finsky.protos.AndroidBuildProto value) {
    value.getClass();
  if (build_ != null &&
        build_ != finsky.protos.AndroidBuildProto.getDefaultInstance()) {
      build_ =
        finsky.protos.AndroidBuildProto.newBuilder(build_).mergeFrom(value).buildPartial();
    } else {
      build_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
   */
  private void clearBuild() {  build_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int LASTCHECKINMSEC_FIELD_NUMBER = 2;
  private long lastCheckinMsec_;
  /**
   * <code>optional int64 lastCheckinMsec = 2;</code>
   * @return Whether the lastCheckinMsec field is set.
   */
  @java.lang.Override
  public boolean hasLastCheckinMsec() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 lastCheckinMsec = 2;</code>
   * @return The lastCheckinMsec.
   */
  @java.lang.Override
  public long getLastCheckinMsec() {
    return lastCheckinMsec_;
  }
  /**
   * <code>optional int64 lastCheckinMsec = 2;</code>
   * @param value The lastCheckinMsec to set.
   */
  private void setLastCheckinMsec(long value) {
    bitField0_ |= 0x00000002;
    lastCheckinMsec_ = value;
  }
  /**
   * <code>optional int64 lastCheckinMsec = 2;</code>
   */
  private void clearLastCheckinMsec() {
    bitField0_ = (bitField0_ & ~0x00000002);
    lastCheckinMsec_ = 0L;
  }

  public static final int EVENT_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<finsky.protos.AndroidEventProto> event_;
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  @java.lang.Override
  public java.util.List<finsky.protos.AndroidEventProto> getEventList() {
    return event_;
  }
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  public java.util.List<? extends finsky.protos.AndroidEventProtoOrBuilder> 
      getEventOrBuilderList() {
    return event_;
  }
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  @java.lang.Override
  public int getEventCount() {
    return event_.size();
  }
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  @java.lang.Override
  public finsky.protos.AndroidEventProto getEvent(int index) {
    return event_.get(index);
  }
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  public finsky.protos.AndroidEventProtoOrBuilder getEventOrBuilder(
      int index) {
    return event_.get(index);
  }
  private void ensureEventIsMutable() {
    com.google.protobuf.Internal.ProtobufList<finsky.protos.AndroidEventProto> tmp = event_;
    if (!tmp.isModifiable()) {
      event_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  private void setEvent(
      int index, finsky.protos.AndroidEventProto value) {
    value.getClass();
  ensureEventIsMutable();
    event_.set(index, value);
  }
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  private void addEvent(finsky.protos.AndroidEventProto value) {
    value.getClass();
  ensureEventIsMutable();
    event_.add(value);
  }
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  private void addEvent(
      int index, finsky.protos.AndroidEventProto value) {
    value.getClass();
  ensureEventIsMutable();
    event_.add(index, value);
  }
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  private void addAllEvent(
      java.lang.Iterable<? extends finsky.protos.AndroidEventProto> values) {
    ensureEventIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, event_);
  }
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  private void clearEvent() {
    event_ = emptyProtobufList();
  }
  /**
   * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
   */
  private void removeEvent(int index) {
    ensureEventIsMutable();
    event_.remove(index);
  }

  public static final int STAT_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<finsky.protos.AndroidStatisticProto> stat_;
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  @java.lang.Override
  public java.util.List<finsky.protos.AndroidStatisticProto> getStatList() {
    return stat_;
  }
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  public java.util.List<? extends finsky.protos.AndroidStatisticProtoOrBuilder> 
      getStatOrBuilderList() {
    return stat_;
  }
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  @java.lang.Override
  public int getStatCount() {
    return stat_.size();
  }
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  @java.lang.Override
  public finsky.protos.AndroidStatisticProto getStat(int index) {
    return stat_.get(index);
  }
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  public finsky.protos.AndroidStatisticProtoOrBuilder getStatOrBuilder(
      int index) {
    return stat_.get(index);
  }
  private void ensureStatIsMutable() {
    com.google.protobuf.Internal.ProtobufList<finsky.protos.AndroidStatisticProto> tmp = stat_;
    if (!tmp.isModifiable()) {
      stat_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  private void setStat(
      int index, finsky.protos.AndroidStatisticProto value) {
    value.getClass();
  ensureStatIsMutable();
    stat_.set(index, value);
  }
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  private void addStat(finsky.protos.AndroidStatisticProto value) {
    value.getClass();
  ensureStatIsMutable();
    stat_.add(value);
  }
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  private void addStat(
      int index, finsky.protos.AndroidStatisticProto value) {
    value.getClass();
  ensureStatIsMutable();
    stat_.add(index, value);
  }
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  private void addAllStat(
      java.lang.Iterable<? extends finsky.protos.AndroidStatisticProto> values) {
    ensureStatIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, stat_);
  }
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  private void clearStat() {
    stat_ = emptyProtobufList();
  }
  /**
   * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
   */
  private void removeStat(int index) {
    ensureStatIsMutable();
    stat_.remove(index);
  }

  public static final int REQUESTEDGROUP_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> requestedGroup_;
  /**
   * <code>repeated string requestedGroup = 5;</code>
   * @return A list containing the requestedGroup.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getRequestedGroupList() {
    return requestedGroup_;
  }
  /**
   * <code>repeated string requestedGroup = 5;</code>
   * @return The count of requestedGroup.
   */
  @java.lang.Override
  public int getRequestedGroupCount() {
    return requestedGroup_.size();
  }
  /**
   * <code>repeated string requestedGroup = 5;</code>
   * @param index The index of the element to return.
   * @return The requestedGroup at the given index.
   */
  @java.lang.Override
  public java.lang.String getRequestedGroup(int index) {
    return requestedGroup_.get(index);
  }
  /**
   * <code>repeated string requestedGroup = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the requestedGroup at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestedGroupBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        requestedGroup_.get(index));
  }
  private void ensureRequestedGroupIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        requestedGroup_;  if (!tmp.isModifiable()) {
      requestedGroup_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string requestedGroup = 5;</code>
   * @param index The index to set the value at.
   * @param value The requestedGroup to set.
   */
  private void setRequestedGroup(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureRequestedGroupIsMutable();
    requestedGroup_.set(index, value);
  }
  /**
   * <code>repeated string requestedGroup = 5;</code>
   * @param value The requestedGroup to add.
   */
  private void addRequestedGroup(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureRequestedGroupIsMutable();
    requestedGroup_.add(value);
  }
  /**
   * <code>repeated string requestedGroup = 5;</code>
   * @param values The requestedGroup to add.
   */
  private void addAllRequestedGroup(
      java.lang.Iterable<java.lang.String> values) {
    ensureRequestedGroupIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, requestedGroup_);
  }
  /**
   * <code>repeated string requestedGroup = 5;</code>
   */
  private void clearRequestedGroup() {
    requestedGroup_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string requestedGroup = 5;</code>
   * @param value The bytes of the requestedGroup to add.
   */
  private void addRequestedGroupBytes(
      com.google.protobuf.ByteString value) {
    ensureRequestedGroupIsMutable();
    requestedGroup_.add(value.toStringUtf8());
  }

  public static final int CELLOPERATOR_FIELD_NUMBER = 6;
  private java.lang.String cellOperator_;
  /**
   * <code>optional string cellOperator = 6;</code>
   * @return Whether the cellOperator field is set.
   */
  @java.lang.Override
  public boolean hasCellOperator() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string cellOperator = 6;</code>
   * @return The cellOperator.
   */
  @java.lang.Override
  public java.lang.String getCellOperator() {
    return cellOperator_;
  }
  /**
   * <code>optional string cellOperator = 6;</code>
   * @return The bytes for cellOperator.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCellOperatorBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(cellOperator_);
  }
  /**
   * <code>optional string cellOperator = 6;</code>
   * @param value The cellOperator to set.
   */
  private void setCellOperator(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
    cellOperator_ = value;
  }
  /**
   * <code>optional string cellOperator = 6;</code>
   */
  private void clearCellOperator() {
    bitField0_ = (bitField0_ & ~0x00000004);
    cellOperator_ = getDefaultInstance().getCellOperator();
  }
  /**
   * <code>optional string cellOperator = 6;</code>
   * @param value The bytes for cellOperator to set.
   */
  private void setCellOperatorBytes(
      com.google.protobuf.ByteString value) {
    cellOperator_ = value.toStringUtf8();
    bitField0_ |= 0x00000004;
  }

  public static final int SIMOPERATOR_FIELD_NUMBER = 7;
  private java.lang.String simOperator_;
  /**
   * <code>optional string simOperator = 7;</code>
   * @return Whether the simOperator field is set.
   */
  @java.lang.Override
  public boolean hasSimOperator() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string simOperator = 7;</code>
   * @return The simOperator.
   */
  @java.lang.Override
  public java.lang.String getSimOperator() {
    return simOperator_;
  }
  /**
   * <code>optional string simOperator = 7;</code>
   * @return The bytes for simOperator.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSimOperatorBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(simOperator_);
  }
  /**
   * <code>optional string simOperator = 7;</code>
   * @param value The simOperator to set.
   */
  private void setSimOperator(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000008;
    simOperator_ = value;
  }
  /**
   * <code>optional string simOperator = 7;</code>
   */
  private void clearSimOperator() {
    bitField0_ = (bitField0_ & ~0x00000008);
    simOperator_ = getDefaultInstance().getSimOperator();
  }
  /**
   * <code>optional string simOperator = 7;</code>
   * @param value The bytes for simOperator to set.
   */
  private void setSimOperatorBytes(
      com.google.protobuf.ByteString value) {
    simOperator_ = value.toStringUtf8();
    bitField0_ |= 0x00000008;
  }

  public static final int ROAMING_FIELD_NUMBER = 8;
  private java.lang.String roaming_;
  /**
   * <code>optional string roaming = 8;</code>
   * @return Whether the roaming field is set.
   */
  @java.lang.Override
  public boolean hasRoaming() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string roaming = 8;</code>
   * @return The roaming.
   */
  @java.lang.Override
  public java.lang.String getRoaming() {
    return roaming_;
  }
  /**
   * <code>optional string roaming = 8;</code>
   * @return The bytes for roaming.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoamingBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(roaming_);
  }
  /**
   * <code>optional string roaming = 8;</code>
   * @param value The roaming to set.
   */
  private void setRoaming(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000010;
    roaming_ = value;
  }
  /**
   * <code>optional string roaming = 8;</code>
   */
  private void clearRoaming() {
    bitField0_ = (bitField0_ & ~0x00000010);
    roaming_ = getDefaultInstance().getRoaming();
  }
  /**
   * <code>optional string roaming = 8;</code>
   * @param value The bytes for roaming to set.
   */
  private void setRoamingBytes(
      com.google.protobuf.ByteString value) {
    roaming_ = value.toStringUtf8();
    bitField0_ |= 0x00000010;
  }

  public static final int USERNUMBER_FIELD_NUMBER = 9;
  private int userNumber_;
  /**
   * <code>optional int32 userNumber = 9;</code>
   * @return Whether the userNumber field is set.
   */
  @java.lang.Override
  public boolean hasUserNumber() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 userNumber = 9;</code>
   * @return The userNumber.
   */
  @java.lang.Override
  public int getUserNumber() {
    return userNumber_;
  }
  /**
   * <code>optional int32 userNumber = 9;</code>
   * @param value The userNumber to set.
   */
  private void setUserNumber(int value) {
    bitField0_ |= 0x00000020;
    userNumber_ = value;
  }
  /**
   * <code>optional int32 userNumber = 9;</code>
   */
  private void clearUserNumber() {
    bitField0_ = (bitField0_ & ~0x00000020);
    userNumber_ = 0;
  }

  public static finsky.protos.AndroidCheckinProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.AndroidCheckinProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.AndroidCheckinProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.AndroidCheckinProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.AndroidCheckinProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.AndroidCheckinProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.AndroidCheckinProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.AndroidCheckinProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static finsky.protos.AndroidCheckinProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static finsky.protos.AndroidCheckinProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.AndroidCheckinProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.AndroidCheckinProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.AndroidCheckinProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.AndroidCheckinProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.AndroidCheckinProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.AndroidCheckinProto)
      finsky.protos.AndroidCheckinProtoOrBuilder {
    // Construct using finsky.protos.AndroidCheckinProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
     */
    @java.lang.Override
    public boolean hasBuild() {
      return instance.hasBuild();
    }
    /**
     * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
     */
    @java.lang.Override
    public finsky.protos.AndroidBuildProto getBuild() {
      return instance.getBuild();
    }
    /**
     * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
     */
    public Builder setBuild(finsky.protos.AndroidBuildProto value) {
      copyOnWrite();
      instance.setBuild(value);
      return this;
      }
    /**
     * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
     */
    public Builder setBuild(
        finsky.protos.AndroidBuildProto.Builder builderForValue) {
      copyOnWrite();
      instance.setBuild(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
     */
    public Builder mergeBuild(finsky.protos.AndroidBuildProto value) {
      copyOnWrite();
      instance.mergeBuild(value);
      return this;
    }
    /**
     * <code>optional .finsky.protos.AndroidBuildProto build = 1;</code>
     */
    public Builder clearBuild() {  copyOnWrite();
      instance.clearBuild();
      return this;
    }

    /**
     * <code>optional int64 lastCheckinMsec = 2;</code>
     * @return Whether the lastCheckinMsec field is set.
     */
    @java.lang.Override
    public boolean hasLastCheckinMsec() {
      return instance.hasLastCheckinMsec();
    }
    /**
     * <code>optional int64 lastCheckinMsec = 2;</code>
     * @return The lastCheckinMsec.
     */
    @java.lang.Override
    public long getLastCheckinMsec() {
      return instance.getLastCheckinMsec();
    }
    /**
     * <code>optional int64 lastCheckinMsec = 2;</code>
     * @param value The lastCheckinMsec to set.
     * @return This builder for chaining.
     */
    public Builder setLastCheckinMsec(long value) {
      copyOnWrite();
      instance.setLastCheckinMsec(value);
      return this;
    }
    /**
     * <code>optional int64 lastCheckinMsec = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastCheckinMsec() {
      copyOnWrite();
      instance.clearLastCheckinMsec();
      return this;
    }

    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    @java.lang.Override
    public java.util.List<finsky.protos.AndroidEventProto> getEventList() {
      return java.util.Collections.unmodifiableList(
          instance.getEventList());
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    @java.lang.Override
    public int getEventCount() {
      return instance.getEventCount();
    }/**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    @java.lang.Override
    public finsky.protos.AndroidEventProto getEvent(int index) {
      return instance.getEvent(index);
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    public Builder setEvent(
        int index, finsky.protos.AndroidEventProto value) {
      copyOnWrite();
      instance.setEvent(index, value);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    public Builder setEvent(
        int index, finsky.protos.AndroidEventProto.Builder builderForValue) {
      copyOnWrite();
      instance.setEvent(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    public Builder addEvent(finsky.protos.AndroidEventProto value) {
      copyOnWrite();
      instance.addEvent(value);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    public Builder addEvent(
        int index, finsky.protos.AndroidEventProto value) {
      copyOnWrite();
      instance.addEvent(index, value);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    public Builder addEvent(
        finsky.protos.AndroidEventProto.Builder builderForValue) {
      copyOnWrite();
      instance.addEvent(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    public Builder addEvent(
        int index, finsky.protos.AndroidEventProto.Builder builderForValue) {
      copyOnWrite();
      instance.addEvent(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    public Builder addAllEvent(
        java.lang.Iterable<? extends finsky.protos.AndroidEventProto> values) {
      copyOnWrite();
      instance.addAllEvent(values);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    public Builder clearEvent() {
      copyOnWrite();
      instance.clearEvent();
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidEventProto event = 3;</code>
     */
    public Builder removeEvent(int index) {
      copyOnWrite();
      instance.removeEvent(index);
      return this;
    }

    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    @java.lang.Override
    public java.util.List<finsky.protos.AndroidStatisticProto> getStatList() {
      return java.util.Collections.unmodifiableList(
          instance.getStatList());
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    @java.lang.Override
    public int getStatCount() {
      return instance.getStatCount();
    }/**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    @java.lang.Override
    public finsky.protos.AndroidStatisticProto getStat(int index) {
      return instance.getStat(index);
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    public Builder setStat(
        int index, finsky.protos.AndroidStatisticProto value) {
      copyOnWrite();
      instance.setStat(index, value);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    public Builder setStat(
        int index, finsky.protos.AndroidStatisticProto.Builder builderForValue) {
      copyOnWrite();
      instance.setStat(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    public Builder addStat(finsky.protos.AndroidStatisticProto value) {
      copyOnWrite();
      instance.addStat(value);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    public Builder addStat(
        int index, finsky.protos.AndroidStatisticProto value) {
      copyOnWrite();
      instance.addStat(index, value);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    public Builder addStat(
        finsky.protos.AndroidStatisticProto.Builder builderForValue) {
      copyOnWrite();
      instance.addStat(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    public Builder addStat(
        int index, finsky.protos.AndroidStatisticProto.Builder builderForValue) {
      copyOnWrite();
      instance.addStat(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    public Builder addAllStat(
        java.lang.Iterable<? extends finsky.protos.AndroidStatisticProto> values) {
      copyOnWrite();
      instance.addAllStat(values);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    public Builder clearStat() {
      copyOnWrite();
      instance.clearStat();
      return this;
    }
    /**
     * <code>repeated .finsky.protos.AndroidStatisticProto stat = 4;</code>
     */
    public Builder removeStat(int index) {
      copyOnWrite();
      instance.removeStat(index);
      return this;
    }

    /**
     * <code>repeated string requestedGroup = 5;</code>
     * @return A list containing the requestedGroup.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getRequestedGroupList() {
      return java.util.Collections.unmodifiableList(
          instance.getRequestedGroupList());
    }
    /**
     * <code>repeated string requestedGroup = 5;</code>
     * @return The count of requestedGroup.
     */
    @java.lang.Override
    public int getRequestedGroupCount() {
      return instance.getRequestedGroupCount();
    }
    /**
     * <code>repeated string requestedGroup = 5;</code>
     * @param index The index of the element to return.
     * @return The requestedGroup at the given index.
     */
    @java.lang.Override
    public java.lang.String getRequestedGroup(int index) {
      return instance.getRequestedGroup(index);
    }
    /**
     * <code>repeated string requestedGroup = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the requestedGroup at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestedGroupBytes(int index) {
      return instance.getRequestedGroupBytes(index);
    }
    /**
     * <code>repeated string requestedGroup = 5;</code>
     * @param index The index to set the value at.
     * @param value The requestedGroup to set.
     * @return This builder for chaining.
     */
    public Builder setRequestedGroup(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setRequestedGroup(index, value);
      return this;
    }
    /**
     * <code>repeated string requestedGroup = 5;</code>
     * @param value The requestedGroup to add.
     * @return This builder for chaining.
     */
    public Builder addRequestedGroup(
        java.lang.String value) {
      copyOnWrite();
      instance.addRequestedGroup(value);
      return this;
    }
    /**
     * <code>repeated string requestedGroup = 5;</code>
     * @param values The requestedGroup to add.
     * @return This builder for chaining.
     */
    public Builder addAllRequestedGroup(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllRequestedGroup(values);
      return this;
    }
    /**
     * <code>repeated string requestedGroup = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestedGroup() {
      copyOnWrite();
      instance.clearRequestedGroup();
      return this;
    }
    /**
     * <code>repeated string requestedGroup = 5;</code>
     * @param value The bytes of the requestedGroup to add.
     * @return This builder for chaining.
     */
    public Builder addRequestedGroupBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addRequestedGroupBytes(value);
      return this;
    }

    /**
     * <code>optional string cellOperator = 6;</code>
     * @return Whether the cellOperator field is set.
     */
    @java.lang.Override
    public boolean hasCellOperator() {
      return instance.hasCellOperator();
    }
    /**
     * <code>optional string cellOperator = 6;</code>
     * @return The cellOperator.
     */
    @java.lang.Override
    public java.lang.String getCellOperator() {
      return instance.getCellOperator();
    }
    /**
     * <code>optional string cellOperator = 6;</code>
     * @return The bytes for cellOperator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCellOperatorBytes() {
      return instance.getCellOperatorBytes();
    }
    /**
     * <code>optional string cellOperator = 6;</code>
     * @param value The cellOperator to set.
     * @return This builder for chaining.
     */
    public Builder setCellOperator(
        java.lang.String value) {
      copyOnWrite();
      instance.setCellOperator(value);
      return this;
    }
    /**
     * <code>optional string cellOperator = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCellOperator() {
      copyOnWrite();
      instance.clearCellOperator();
      return this;
    }
    /**
     * <code>optional string cellOperator = 6;</code>
     * @param value The bytes for cellOperator to set.
     * @return This builder for chaining.
     */
    public Builder setCellOperatorBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCellOperatorBytes(value);
      return this;
    }

    /**
     * <code>optional string simOperator = 7;</code>
     * @return Whether the simOperator field is set.
     */
    @java.lang.Override
    public boolean hasSimOperator() {
      return instance.hasSimOperator();
    }
    /**
     * <code>optional string simOperator = 7;</code>
     * @return The simOperator.
     */
    @java.lang.Override
    public java.lang.String getSimOperator() {
      return instance.getSimOperator();
    }
    /**
     * <code>optional string simOperator = 7;</code>
     * @return The bytes for simOperator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSimOperatorBytes() {
      return instance.getSimOperatorBytes();
    }
    /**
     * <code>optional string simOperator = 7;</code>
     * @param value The simOperator to set.
     * @return This builder for chaining.
     */
    public Builder setSimOperator(
        java.lang.String value) {
      copyOnWrite();
      instance.setSimOperator(value);
      return this;
    }
    /**
     * <code>optional string simOperator = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSimOperator() {
      copyOnWrite();
      instance.clearSimOperator();
      return this;
    }
    /**
     * <code>optional string simOperator = 7;</code>
     * @param value The bytes for simOperator to set.
     * @return This builder for chaining.
     */
    public Builder setSimOperatorBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSimOperatorBytes(value);
      return this;
    }

    /**
     * <code>optional string roaming = 8;</code>
     * @return Whether the roaming field is set.
     */
    @java.lang.Override
    public boolean hasRoaming() {
      return instance.hasRoaming();
    }
    /**
     * <code>optional string roaming = 8;</code>
     * @return The roaming.
     */
    @java.lang.Override
    public java.lang.String getRoaming() {
      return instance.getRoaming();
    }
    /**
     * <code>optional string roaming = 8;</code>
     * @return The bytes for roaming.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoamingBytes() {
      return instance.getRoamingBytes();
    }
    /**
     * <code>optional string roaming = 8;</code>
     * @param value The roaming to set.
     * @return This builder for chaining.
     */
    public Builder setRoaming(
        java.lang.String value) {
      copyOnWrite();
      instance.setRoaming(value);
      return this;
    }
    /**
     * <code>optional string roaming = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoaming() {
      copyOnWrite();
      instance.clearRoaming();
      return this;
    }
    /**
     * <code>optional string roaming = 8;</code>
     * @param value The bytes for roaming to set.
     * @return This builder for chaining.
     */
    public Builder setRoamingBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRoamingBytes(value);
      return this;
    }

    /**
     * <code>optional int32 userNumber = 9;</code>
     * @return Whether the userNumber field is set.
     */
    @java.lang.Override
    public boolean hasUserNumber() {
      return instance.hasUserNumber();
    }
    /**
     * <code>optional int32 userNumber = 9;</code>
     * @return The userNumber.
     */
    @java.lang.Override
    public int getUserNumber() {
      return instance.getUserNumber();
    }
    /**
     * <code>optional int32 userNumber = 9;</code>
     * @param value The userNumber to set.
     * @return This builder for chaining.
     */
    public Builder setUserNumber(int value) {
      copyOnWrite();
      instance.setUserNumber(value);
      return this;
    }
    /**
     * <code>optional int32 userNumber = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserNumber() {
      copyOnWrite();
      instance.clearUserNumber();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.AndroidCheckinProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.AndroidCheckinProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "build_",
            "lastCheckinMsec_",
            "event_",
            finsky.protos.AndroidEventProto.class,
            "stat_",
            finsky.protos.AndroidStatisticProto.class,
            "requestedGroup_",
            "cellOperator_",
            "simOperator_",
            "roaming_",
            "userNumber_",
          };
          java.lang.String info =
              "\u0001\t\u0000\u0001\u0001\t\t\u0000\u0003\u0000\u0001\u1009\u0000\u0002\u1002\u0001" +
              "\u0003\u001b\u0004\u001b\u0005\u001a\u0006\u1008\u0002\u0007\u1008\u0003\b\u1008" +
              "\u0004\t\u1004\u0005";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.AndroidCheckinProto> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.AndroidCheckinProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.AndroidCheckinProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.AndroidCheckinProto)
  private static final finsky.protos.AndroidCheckinProto DEFAULT_INSTANCE;
  static {
    AndroidCheckinProto defaultInstance = new AndroidCheckinProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AndroidCheckinProto.class, defaultInstance);
  }

  public static finsky.protos.AndroidCheckinProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AndroidCheckinProto> PARSER;

  public static com.google.protobuf.Parser<AndroidCheckinProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

