// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.AnnotationLink}
 */
public  final class AnnotationLink extends
    com.google.protobuf.GeneratedMessageLite<
        AnnotationLink, AnnotationLink.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.AnnotationLink)
    AnnotationLinkOrBuilder {
  private AnnotationLink() {
    uri_ = "";
  }
  private int bitField0_;
  public static final int URI_FIELD_NUMBER = 1;
  private java.lang.String uri_;
  /**
   * <code>optional string uri = 1;</code>
   * @return Whether the uri field is set.
   */
  @java.lang.Override
  public boolean hasUri() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string uri = 1;</code>
   * @return The uri.
   */
  @java.lang.Override
  public java.lang.String getUri() {
    return uri_;
  }
  /**
   * <code>optional string uri = 1;</code>
   * @return The bytes for uri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUriBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uri_);
  }
  /**
   * <code>optional string uri = 1;</code>
   * @param value The uri to set.
   */
  private void setUri(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    uri_ = value;
  }
  /**
   * <code>optional string uri = 1;</code>
   */
  private void clearUri() {
    bitField0_ = (bitField0_ & ~0x00000001);
    uri_ = getDefaultInstance().getUri();
  }
  /**
   * <code>optional string uri = 1;</code>
   * @param value The bytes for uri to set.
   */
  private void setUriBytes(
      com.google.protobuf.ByteString value) {
    uri_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int RESOLVEDLINK_FIELD_NUMBER = 2;
  private finsky.protos.ResolvedLink resolvedLink_;
  /**
   * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
   */
  @java.lang.Override
  public boolean hasResolvedLink() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
   */
  @java.lang.Override
  public finsky.protos.ResolvedLink getResolvedLink() {
    return resolvedLink_ == null ? finsky.protos.ResolvedLink.getDefaultInstance() : resolvedLink_;
  }
  /**
   * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
   */
  private void setResolvedLink(finsky.protos.ResolvedLink value) {
    value.getClass();
  resolvedLink_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeResolvedLink(finsky.protos.ResolvedLink value) {
    value.getClass();
  if (resolvedLink_ != null &&
        resolvedLink_ != finsky.protos.ResolvedLink.getDefaultInstance()) {
      resolvedLink_ =
        finsky.protos.ResolvedLink.newBuilder(resolvedLink_).mergeFrom(value).buildPartial();
    } else {
      resolvedLink_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
   */
  private void clearResolvedLink() {  resolvedLink_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int URIBACKEND_FIELD_NUMBER = 3;
  private int uriBackend_;
  /**
   * <code>optional int32 uriBackend = 3;</code>
   * @return Whether the uriBackend field is set.
   */
  @java.lang.Override
  public boolean hasUriBackend() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 uriBackend = 3;</code>
   * @return The uriBackend.
   */
  @java.lang.Override
  public int getUriBackend() {
    return uriBackend_;
  }
  /**
   * <code>optional int32 uriBackend = 3;</code>
   * @param value The uriBackend to set.
   */
  private void setUriBackend(int value) {
    bitField0_ |= 0x00000004;
    uriBackend_ = value;
  }
  /**
   * <code>optional int32 uriBackend = 3;</code>
   */
  private void clearUriBackend() {
    bitField0_ = (bitField0_ & ~0x00000004);
    uriBackend_ = 0;
  }

  public static finsky.protos.AnnotationLink parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.AnnotationLink parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.AnnotationLink parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.AnnotationLink parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.AnnotationLink parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.AnnotationLink parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.AnnotationLink parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.AnnotationLink parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static finsky.protos.AnnotationLink parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static finsky.protos.AnnotationLink parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.AnnotationLink parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.AnnotationLink parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.AnnotationLink prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.AnnotationLink}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.AnnotationLink, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.AnnotationLink)
      finsky.protos.AnnotationLinkOrBuilder {
    // Construct using finsky.protos.AnnotationLink.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string uri = 1;</code>
     * @return Whether the uri field is set.
     */
    @java.lang.Override
    public boolean hasUri() {
      return instance.hasUri();
    }
    /**
     * <code>optional string uri = 1;</code>
     * @return The uri.
     */
    @java.lang.Override
    public java.lang.String getUri() {
      return instance.getUri();
    }
    /**
     * <code>optional string uri = 1;</code>
     * @return The bytes for uri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUriBytes() {
      return instance.getUriBytes();
    }
    /**
     * <code>optional string uri = 1;</code>
     * @param value The uri to set.
     * @return This builder for chaining.
     */
    public Builder setUri(
        java.lang.String value) {
      copyOnWrite();
      instance.setUri(value);
      return this;
    }
    /**
     * <code>optional string uri = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUri() {
      copyOnWrite();
      instance.clearUri();
      return this;
    }
    /**
     * <code>optional string uri = 1;</code>
     * @param value The bytes for uri to set.
     * @return This builder for chaining.
     */
    public Builder setUriBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUriBytes(value);
      return this;
    }

    /**
     * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
     */
    @java.lang.Override
    public boolean hasResolvedLink() {
      return instance.hasResolvedLink();
    }
    /**
     * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
     */
    @java.lang.Override
    public finsky.protos.ResolvedLink getResolvedLink() {
      return instance.getResolvedLink();
    }
    /**
     * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
     */
    public Builder setResolvedLink(finsky.protos.ResolvedLink value) {
      copyOnWrite();
      instance.setResolvedLink(value);
      return this;
      }
    /**
     * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
     */
    public Builder setResolvedLink(
        finsky.protos.ResolvedLink.Builder builderForValue) {
      copyOnWrite();
      instance.setResolvedLink(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
     */
    public Builder mergeResolvedLink(finsky.protos.ResolvedLink value) {
      copyOnWrite();
      instance.mergeResolvedLink(value);
      return this;
    }
    /**
     * <code>optional .finsky.protos.ResolvedLink resolvedLink = 2;</code>
     */
    public Builder clearResolvedLink() {  copyOnWrite();
      instance.clearResolvedLink();
      return this;
    }

    /**
     * <code>optional int32 uriBackend = 3;</code>
     * @return Whether the uriBackend field is set.
     */
    @java.lang.Override
    public boolean hasUriBackend() {
      return instance.hasUriBackend();
    }
    /**
     * <code>optional int32 uriBackend = 3;</code>
     * @return The uriBackend.
     */
    @java.lang.Override
    public int getUriBackend() {
      return instance.getUriBackend();
    }
    /**
     * <code>optional int32 uriBackend = 3;</code>
     * @param value The uriBackend to set.
     * @return This builder for chaining.
     */
    public Builder setUriBackend(int value) {
      copyOnWrite();
      instance.setUriBackend(value);
      return this;
    }
    /**
     * <code>optional int32 uriBackend = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUriBackend() {
      copyOnWrite();
      instance.clearUriBackend();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.AnnotationLink)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.AnnotationLink();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "uri_",
            "resolvedLink_",
            "uriBackend_",
          };
          java.lang.String info =
              "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1008\u0000\u0002" +
              "\u1009\u0001\u0003\u1004\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.AnnotationLink> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.AnnotationLink.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.AnnotationLink>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.AnnotationLink)
  private static final finsky.protos.AnnotationLink DEFAULT_INSTANCE;
  static {
    AnnotationLink defaultInstance = new AnnotationLink();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AnnotationLink.class, defaultInstance);
  }

  public static finsky.protos.AnnotationLink getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AnnotationLink> PARSER;

  public static com.google.protobuf.Parser<AnnotationLink> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

