// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

public interface CategoryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.CategoryInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string appType = 1;</code>
   * @return Whether the appType field is set.
   */
  boolean hasAppType();
  /**
   * <code>optional string appType = 1;</code>
   * @return The appType.
   */
  java.lang.String getAppType();
  /**
   * <code>optional string appType = 1;</code>
   * @return The bytes for appType.
   */
  com.google.protobuf.ByteString
      getAppTypeBytes();

  /**
   * <code>optional string appCategory = 2;</code>
   * @return Whether the appCategory field is set.
   */
  boolean hasAppCategory();
  /**
   * <code>optional string appCategory = 2;</code>
   * @return The appCategory.
   */
  java.lang.String getAppCategory();
  /**
   * <code>optional string appCategory = 2;</code>
   * @return The bytes for appCategory.
   */
  com.google.protobuf.ByteString
      getAppCategoryBytes();
}
