// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

public interface CommonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.Common)
    com.google.protobuf.MessageLiteOrBuilder {
}
