// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

public interface DocV2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.DocV2)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string docid = 1;</code>
   * @return Whether the docid field is set.
   */
  boolean hasDocid();
  /**
   * <code>optional string docid = 1;</code>
   * @return The docid.
   */
  java.lang.String getDocid();
  /**
   * <code>optional string docid = 1;</code>
   * @return The bytes for docid.
   */
  com.google.protobuf.ByteString
      getDocidBytes();

  /**
   * <code>optional string backendDocid = 2;</code>
   * @return Whether the backendDocid field is set.
   */
  boolean hasBackendDocid();
  /**
   * <code>optional string backendDocid = 2;</code>
   * @return The backendDocid.
   */
  java.lang.String getBackendDocid();
  /**
   * <code>optional string backendDocid = 2;</code>
   * @return The bytes for backendDocid.
   */
  com.google.protobuf.ByteString
      getBackendDocidBytes();

  /**
   * <code>optional int32 docType = 3;</code>
   * @return Whether the docType field is set.
   */
  boolean hasDocType();
  /**
   * <code>optional int32 docType = 3;</code>
   * @return The docType.
   */
  int getDocType();

  /**
   * <code>optional int32 backendId = 4;</code>
   * @return Whether the backendId field is set.
   */
  boolean hasBackendId();
  /**
   * <code>optional int32 backendId = 4;</code>
   * @return The backendId.
   */
  int getBackendId();

  /**
   * <code>optional string title = 5;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>optional string title = 5;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 5;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional string creator = 6;</code>
   * @return Whether the creator field is set.
   */
  boolean hasCreator();
  /**
   * <code>optional string creator = 6;</code>
   * @return The creator.
   */
  java.lang.String getCreator();
  /**
   * <code>optional string creator = 6;</code>
   * @return The bytes for creator.
   */
  com.google.protobuf.ByteString
      getCreatorBytes();

  /**
   * <code>optional string descriptionHtml = 7;</code>
   * @return Whether the descriptionHtml field is set.
   */
  boolean hasDescriptionHtml();
  /**
   * <code>optional string descriptionHtml = 7;</code>
   * @return The descriptionHtml.
   */
  java.lang.String getDescriptionHtml();
  /**
   * <code>optional string descriptionHtml = 7;</code>
   * @return The bytes for descriptionHtml.
   */
  com.google.protobuf.ByteString
      getDescriptionHtmlBytes();

  /**
   * <code>repeated .finsky.protos.Common.Offer offer = 8;</code>
   */
  java.util.List<finsky.protos.Common.Offer> 
      getOfferList();
  /**
   * <code>repeated .finsky.protos.Common.Offer offer = 8;</code>
   */
  finsky.protos.Common.Offer getOffer(int index);
  /**
   * <code>repeated .finsky.protos.Common.Offer offer = 8;</code>
   */
  int getOfferCount();

  /**
   * <pre>
   *optional Availability availability = 9;
   * </pre>
   *
   * <code>repeated .finsky.protos.Common.Image image = 10;</code>
   */
  java.util.List<finsky.protos.Common.Image> 
      getImageList();
  /**
   * <pre>
   *optional Availability availability = 9;
   * </pre>
   *
   * <code>repeated .finsky.protos.Common.Image image = 10;</code>
   */
  finsky.protos.Common.Image getImage(int index);
  /**
   * <pre>
   *optional Availability availability = 9;
   * </pre>
   *
   * <code>repeated .finsky.protos.Common.Image image = 10;</code>
   */
  int getImageCount();

  /**
   * <code>repeated .finsky.protos.DocV2 child = 11;</code>
   */
  java.util.List<finsky.protos.DocV2> 
      getChildList();
  /**
   * <code>repeated .finsky.protos.DocV2 child = 11;</code>
   */
  finsky.protos.DocV2 getChild(int index);
  /**
   * <code>repeated .finsky.protos.DocV2 child = 11;</code>
   */
  int getChildCount();

  /**
   * <code>optional .finsky.protos.Containers.ContainerMetadata containerMetadata = 12;</code>
   * @return Whether the containerMetadata field is set.
   */
  boolean hasContainerMetadata();
  /**
   * <code>optional .finsky.protos.Containers.ContainerMetadata containerMetadata = 12;</code>
   * @return The containerMetadata.
   */
  finsky.protos.Containers.ContainerMetadata getContainerMetadata();

  /**
   * <code>optional .finsky.protos.DocDetails details = 13;</code>
   * @return Whether the details field is set.
   */
  boolean hasDetails();
  /**
   * <code>optional .finsky.protos.DocDetails details = 13;</code>
   * @return The details.
   */
  finsky.protos.DocDetails getDetails();

  /**
   * <code>optional .finsky.protos.DocV2.AggregateRating aggregateRating = 14;</code>
   * @return Whether the aggregateRating field is set.
   */
  boolean hasAggregateRating();
  /**
   * <code>optional .finsky.protos.DocV2.AggregateRating aggregateRating = 14;</code>
   * @return The aggregateRating.
   */
  finsky.protos.DocV2.AggregateRating getAggregateRating();

  /**
   * <code>optional .finsky.protos.RelatedLinks relatedLinks = 15;</code>
   * @return Whether the relatedLinks field is set.
   */
  boolean hasRelatedLinks();
  /**
   * <code>optional .finsky.protos.RelatedLinks relatedLinks = 15;</code>
   * @return The relatedLinks.
   */
  finsky.protos.RelatedLinks getRelatedLinks();

  /**
   * <code>optional string detailsUrl = 16;</code>
   * @return Whether the detailsUrl field is set.
   */
  boolean hasDetailsUrl();
  /**
   * <code>optional string detailsUrl = 16;</code>
   * @return The detailsUrl.
   */
  java.lang.String getDetailsUrl();
  /**
   * <code>optional string detailsUrl = 16;</code>
   * @return The bytes for detailsUrl.
   */
  com.google.protobuf.ByteString
      getDetailsUrlBytes();

  /**
   * <code>optional string shareUrl = 17;</code>
   * @return Whether the shareUrl field is set.
   */
  boolean hasShareUrl();
  /**
   * <code>optional string shareUrl = 17;</code>
   * @return The shareUrl.
   */
  java.lang.String getShareUrl();
  /**
   * <code>optional string shareUrl = 17;</code>
   * @return The bytes for shareUrl.
   */
  com.google.protobuf.ByteString
      getShareUrlBytes();

  /**
   * <code>optional string reviewsUrl = 18;</code>
   * @return Whether the reviewsUrl field is set.
   */
  boolean hasReviewsUrl();
  /**
   * <code>optional string reviewsUrl = 18;</code>
   * @return The reviewsUrl.
   */
  java.lang.String getReviewsUrl();
  /**
   * <code>optional string reviewsUrl = 18;</code>
   * @return The bytes for reviewsUrl.
   */
  com.google.protobuf.ByteString
      getReviewsUrlBytes();

  /**
   * <code>optional string backendUrl = 19;</code>
   * @return Whether the backendUrl field is set.
   */
  boolean hasBackendUrl();
  /**
   * <code>optional string backendUrl = 19;</code>
   * @return The backendUrl.
   */
  java.lang.String getBackendUrl();
  /**
   * <code>optional string backendUrl = 19;</code>
   * @return The bytes for backendUrl.
   */
  com.google.protobuf.ByteString
      getBackendUrlBytes();

  /**
   * <code>optional string purchaseDetailsUrl = 20;</code>
   * @return Whether the purchaseDetailsUrl field is set.
   */
  boolean hasPurchaseDetailsUrl();
  /**
   * <code>optional string purchaseDetailsUrl = 20;</code>
   * @return The purchaseDetailsUrl.
   */
  java.lang.String getPurchaseDetailsUrl();
  /**
   * <code>optional string purchaseDetailsUrl = 20;</code>
   * @return The bytes for purchaseDetailsUrl.
   */
  com.google.protobuf.ByteString
      getPurchaseDetailsUrlBytes();

  /**
   * <code>optional bool detailsReusable = 21;</code>
   * @return Whether the detailsReusable field is set.
   */
  boolean hasDetailsReusable();
  /**
   * <code>optional bool detailsReusable = 21;</code>
   * @return The detailsReusable.
   */
  boolean getDetailsReusable();

  /**
   * <code>optional string subtitle = 22;</code>
   * @return Whether the subtitle field is set.
   */
  boolean hasSubtitle();
  /**
   * <code>optional string subtitle = 22;</code>
   * @return The subtitle.
   */
  java.lang.String getSubtitle();
  /**
   * <code>optional string subtitle = 22;</code>
   * @return The bytes for subtitle.
   */
  com.google.protobuf.ByteString
      getSubtitleBytes();

  /**
   * <pre>
   *optional Unknown25 unknown25 = 25;
   * </pre>
   *
   * <code>optional string descriptionShort = 27;</code>
   * @return Whether the descriptionShort field is set.
   */
  boolean hasDescriptionShort();
  /**
   * <pre>
   *optional Unknown25 unknown25 = 25;
   * </pre>
   *
   * <code>optional string descriptionShort = 27;</code>
   * @return The descriptionShort.
   */
  java.lang.String getDescriptionShort();
  /**
   * <pre>
   *optional Unknown25 unknown25 = 25;
   * </pre>
   *
   * <code>optional string descriptionShort = 27;</code>
   * @return The bytes for descriptionShort.
   */
  com.google.protobuf.ByteString
      getDescriptionShortBytes();

  /**
   * <code>optional string reviewSnippetsUrl = 31;</code>
   * @return Whether the reviewSnippetsUrl field is set.
   */
  boolean hasReviewSnippetsUrl();
  /**
   * <code>optional string reviewSnippetsUrl = 31;</code>
   * @return The reviewSnippetsUrl.
   */
  java.lang.String getReviewSnippetsUrl();
  /**
   * <code>optional string reviewSnippetsUrl = 31;</code>
   * @return The bytes for reviewSnippetsUrl.
   */
  com.google.protobuf.ByteString
      getReviewSnippetsUrlBytes();

  /**
   * <code>optional string reviewQuestionsUrl = 34;</code>
   * @return Whether the reviewQuestionsUrl field is set.
   */
  boolean hasReviewQuestionsUrl();
  /**
   * <code>optional string reviewQuestionsUrl = 34;</code>
   * @return The reviewQuestionsUrl.
   */
  java.lang.String getReviewQuestionsUrl();
  /**
   * <code>optional string reviewQuestionsUrl = 34;</code>
   * @return The bytes for reviewQuestionsUrl.
   */
  com.google.protobuf.ByteString
      getReviewQuestionsUrlBytes();
}
