// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.EncodedTargets}
 */
public  final class EncodedTargets extends
    com.google.protobuf.GeneratedMessageLite<
        EncodedTargets, EncodedTargets.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.EncodedTargets)
    EncodedTargetsOrBuilder {
  private EncodedTargets() {
    supportedTarget_ = emptyLongList();
    otherTarget_ = emptyLongList();
  }
  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>optional int32 version = 1;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }
  /**
   * <code>optional int32 version = 1;</code>
   * @param value The version to set.
   */
  private void setVersion(int value) {
    bitField0_ |= 0x00000001;
    version_ = value;
  }
  /**
   * <code>optional int32 version = 1;</code>
   */
  private void clearVersion() {
    bitField0_ = (bitField0_ & ~0x00000001);
    version_ = 0;
  }

  public static final int SUPPORTEDTARGET_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.LongList supportedTarget_;
  /**
   * <code>repeated int64 supportedTarget = 2;</code>
   * @return A list containing the supportedTarget.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getSupportedTargetList() {
    return supportedTarget_;
  }
  /**
   * <code>repeated int64 supportedTarget = 2;</code>
   * @return The count of supportedTarget.
   */
  @java.lang.Override
  public int getSupportedTargetCount() {
    return supportedTarget_.size();
  }
  /**
   * <code>repeated int64 supportedTarget = 2;</code>
   * @param index The index of the element to return.
   * @return The supportedTarget at the given index.
   */
  @java.lang.Override
  public long getSupportedTarget(int index) {
    return supportedTarget_.getLong(index);
  }
  private void ensureSupportedTargetIsMutable() {
    com.google.protobuf.Internal.LongList tmp = supportedTarget_;
    if (!tmp.isModifiable()) {
      supportedTarget_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated int64 supportedTarget = 2;</code>
   * @param index The index to set the value at.
   * @param value The supportedTarget to set.
   */
  private void setSupportedTarget(
      int index, long value) {
    ensureSupportedTargetIsMutable();
    supportedTarget_.setLong(index, value);
  }
  /**
   * <code>repeated int64 supportedTarget = 2;</code>
   * @param value The supportedTarget to add.
   */
  private void addSupportedTarget(long value) {
    ensureSupportedTargetIsMutable();
    supportedTarget_.addLong(value);
  }
  /**
   * <code>repeated int64 supportedTarget = 2;</code>
   * @param values The supportedTarget to add.
   */
  private void addAllSupportedTarget(
      java.lang.Iterable<? extends java.lang.Long> values) {
    ensureSupportedTargetIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, supportedTarget_);
  }
  /**
   * <code>repeated int64 supportedTarget = 2;</code>
   */
  private void clearSupportedTarget() {
    supportedTarget_ = emptyLongList();
  }

  public static final int OTHERTARGET_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.LongList otherTarget_;
  /**
   * <code>repeated int64 otherTarget = 3;</code>
   * @return A list containing the otherTarget.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getOtherTargetList() {
    return otherTarget_;
  }
  /**
   * <code>repeated int64 otherTarget = 3;</code>
   * @return The count of otherTarget.
   */
  @java.lang.Override
  public int getOtherTargetCount() {
    return otherTarget_.size();
  }
  /**
   * <code>repeated int64 otherTarget = 3;</code>
   * @param index The index of the element to return.
   * @return The otherTarget at the given index.
   */
  @java.lang.Override
  public long getOtherTarget(int index) {
    return otherTarget_.getLong(index);
  }
  private void ensureOtherTargetIsMutable() {
    com.google.protobuf.Internal.LongList tmp = otherTarget_;
    if (!tmp.isModifiable()) {
      otherTarget_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated int64 otherTarget = 3;</code>
   * @param index The index to set the value at.
   * @param value The otherTarget to set.
   */
  private void setOtherTarget(
      int index, long value) {
    ensureOtherTargetIsMutable();
    otherTarget_.setLong(index, value);
  }
  /**
   * <code>repeated int64 otherTarget = 3;</code>
   * @param value The otherTarget to add.
   */
  private void addOtherTarget(long value) {
    ensureOtherTargetIsMutable();
    otherTarget_.addLong(value);
  }
  /**
   * <code>repeated int64 otherTarget = 3;</code>
   * @param values The otherTarget to add.
   */
  private void addAllOtherTarget(
      java.lang.Iterable<? extends java.lang.Long> values) {
    ensureOtherTargetIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, otherTarget_);
  }
  /**
   * <code>repeated int64 otherTarget = 3;</code>
   */
  private void clearOtherTarget() {
    otherTarget_ = emptyLongList();
  }

  public static finsky.protos.EncodedTargets parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.EncodedTargets parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.EncodedTargets parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.EncodedTargets parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.EncodedTargets parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.EncodedTargets parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.EncodedTargets parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.EncodedTargets parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.EncodedTargets parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.EncodedTargets parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.EncodedTargets parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.EncodedTargets parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.EncodedTargets prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.EncodedTargets}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.EncodedTargets, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.EncodedTargets)
      finsky.protos.EncodedTargetsOrBuilder {
    // Construct using finsky.protos.EncodedTargets.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 version = 1;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return instance.hasVersion();
    }
    /**
     * <code>optional int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>optional int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>optional int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }

    /**
     * <code>repeated int64 supportedTarget = 2;</code>
     * @return A list containing the supportedTarget.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getSupportedTargetList() {
      return java.util.Collections.unmodifiableList(
          instance.getSupportedTargetList());
    }
    /**
     * <code>repeated int64 supportedTarget = 2;</code>
     * @return The count of supportedTarget.
     */
    @java.lang.Override
    public int getSupportedTargetCount() {
      return instance.getSupportedTargetCount();
    }
    /**
     * <code>repeated int64 supportedTarget = 2;</code>
     * @param index The index of the element to return.
     * @return The supportedTarget at the given index.
     */
    @java.lang.Override
    public long getSupportedTarget(int index) {
      return instance.getSupportedTarget(index);
    }
    /**
     * <code>repeated int64 supportedTarget = 2;</code>
     * @param value The supportedTarget to set.
     * @return This builder for chaining.
     */
    public Builder setSupportedTarget(
        int index, long value) {
      copyOnWrite();
      instance.setSupportedTarget(index, value);
      return this;
    }
    /**
     * <code>repeated int64 supportedTarget = 2;</code>
     * @param value The supportedTarget to add.
     * @return This builder for chaining.
     */
    public Builder addSupportedTarget(long value) {
      copyOnWrite();
      instance.addSupportedTarget(value);
      return this;
    }
    /**
     * <code>repeated int64 supportedTarget = 2;</code>
     * @param values The supportedTarget to add.
     * @return This builder for chaining.
     */
    public Builder addAllSupportedTarget(
        java.lang.Iterable<? extends java.lang.Long> values) {
      copyOnWrite();
      instance.addAllSupportedTarget(values);
      return this;
    }
    /**
     * <code>repeated int64 supportedTarget = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSupportedTarget() {
      copyOnWrite();
      instance.clearSupportedTarget();
      return this;
    }

    /**
     * <code>repeated int64 otherTarget = 3;</code>
     * @return A list containing the otherTarget.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getOtherTargetList() {
      return java.util.Collections.unmodifiableList(
          instance.getOtherTargetList());
    }
    /**
     * <code>repeated int64 otherTarget = 3;</code>
     * @return The count of otherTarget.
     */
    @java.lang.Override
    public int getOtherTargetCount() {
      return instance.getOtherTargetCount();
    }
    /**
     * <code>repeated int64 otherTarget = 3;</code>
     * @param index The index of the element to return.
     * @return The otherTarget at the given index.
     */
    @java.lang.Override
    public long getOtherTarget(int index) {
      return instance.getOtherTarget(index);
    }
    /**
     * <code>repeated int64 otherTarget = 3;</code>
     * @param value The otherTarget to set.
     * @return This builder for chaining.
     */
    public Builder setOtherTarget(
        int index, long value) {
      copyOnWrite();
      instance.setOtherTarget(index, value);
      return this;
    }
    /**
     * <code>repeated int64 otherTarget = 3;</code>
     * @param value The otherTarget to add.
     * @return This builder for chaining.
     */
    public Builder addOtherTarget(long value) {
      copyOnWrite();
      instance.addOtherTarget(value);
      return this;
    }
    /**
     * <code>repeated int64 otherTarget = 3;</code>
     * @param values The otherTarget to add.
     * @return This builder for chaining.
     */
    public Builder addAllOtherTarget(
        java.lang.Iterable<? extends java.lang.Long> values) {
      copyOnWrite();
      instance.addAllOtherTarget(values);
      return this;
    }
    /**
     * <code>repeated int64 otherTarget = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOtherTarget() {
      copyOnWrite();
      instance.clearOtherTarget();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.EncodedTargets)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.EncodedTargets();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "version_",
            "supportedTarget_",
            "otherTarget_",
          };
          java.lang.String info =
              "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0002\u0000\u0001\u1004\u0000\u0002" +
              "\u0014\u0003\u0014";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.EncodedTargets> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.EncodedTargets.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.EncodedTargets>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.EncodedTargets)
  private static final finsky.protos.EncodedTargets DEFAULT_INSTANCE;
  static {
    EncodedTargets defaultInstance = new EncodedTargets();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EncodedTargets.class, defaultInstance);
  }

  public static finsky.protos.EncodedTargets getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EncodedTargets> PARSER;

  public static com.google.protobuf.Parser<EncodedTargets> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

