// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.LibraryReplicationResponse}
 */
public  final class LibraryReplicationResponse extends
    com.google.protobuf.GeneratedMessageLite<
        LibraryReplicationResponse, LibraryReplicationResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.LibraryReplicationResponse)
    LibraryReplicationResponseOrBuilder {
  private LibraryReplicationResponse() {
    update_ = emptyProtobufList();
    autoAcquireFreeAppIfHigherVersionAvailableTag_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int UPDATE_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<finsky.protos.LibraryUpdateProto.LibraryUpdate> update_;
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  @java.lang.Override
  public java.util.List<finsky.protos.LibraryUpdateProto.LibraryUpdate> getUpdateList() {
    return update_;
  }
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  public java.util.List<? extends finsky.protos.LibraryUpdateProto.LibraryUpdateOrBuilder> 
      getUpdateOrBuilderList() {
    return update_;
  }
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  @java.lang.Override
  public int getUpdateCount() {
    return update_.size();
  }
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  @java.lang.Override
  public finsky.protos.LibraryUpdateProto.LibraryUpdate getUpdate(int index) {
    return update_.get(index);
  }
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  public finsky.protos.LibraryUpdateProto.LibraryUpdateOrBuilder getUpdateOrBuilder(
      int index) {
    return update_.get(index);
  }
  private void ensureUpdateIsMutable() {
    com.google.protobuf.Internal.ProtobufList<finsky.protos.LibraryUpdateProto.LibraryUpdate> tmp = update_;
    if (!tmp.isModifiable()) {
      update_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  private void setUpdate(
      int index, finsky.protos.LibraryUpdateProto.LibraryUpdate value) {
    value.getClass();
  ensureUpdateIsMutable();
    update_.set(index, value);
  }
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  private void addUpdate(finsky.protos.LibraryUpdateProto.LibraryUpdate value) {
    value.getClass();
  ensureUpdateIsMutable();
    update_.add(value);
  }
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  private void addUpdate(
      int index, finsky.protos.LibraryUpdateProto.LibraryUpdate value) {
    value.getClass();
  ensureUpdateIsMutable();
    update_.add(index, value);
  }
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  private void addAllUpdate(
      java.lang.Iterable<? extends finsky.protos.LibraryUpdateProto.LibraryUpdate> values) {
    ensureUpdateIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, update_);
  }
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  private void clearUpdate() {
    update_ = emptyProtobufList();
  }
  /**
   * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
   */
  private void removeUpdate(int index) {
    ensureUpdateIsMutable();
    update_.remove(index);
  }

  public static final int AUTOACQUIREFREEAPPIFHIGHERVERSIONAVAILABLETAG_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> autoAcquireFreeAppIfHigherVersionAvailableTag_;
  /**
   * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
   * @return A list containing the autoAcquireFreeAppIfHigherVersionAvailableTag.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getAutoAcquireFreeAppIfHigherVersionAvailableTagList() {
    return autoAcquireFreeAppIfHigherVersionAvailableTag_;
  }
  /**
   * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
   * @return The count of autoAcquireFreeAppIfHigherVersionAvailableTag.
   */
  @java.lang.Override
  public int getAutoAcquireFreeAppIfHigherVersionAvailableTagCount() {
    return autoAcquireFreeAppIfHigherVersionAvailableTag_.size();
  }
  /**
   * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
   * @param index The index of the element to return.
   * @return The autoAcquireFreeAppIfHigherVersionAvailableTag at the given index.
   */
  @java.lang.Override
  public java.lang.String getAutoAcquireFreeAppIfHigherVersionAvailableTag(int index) {
    return autoAcquireFreeAppIfHigherVersionAvailableTag_.get(index);
  }
  /**
   * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the autoAcquireFreeAppIfHigherVersionAvailableTag at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAutoAcquireFreeAppIfHigherVersionAvailableTagBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        autoAcquireFreeAppIfHigherVersionAvailableTag_.get(index));
  }
  private void ensureAutoAcquireFreeAppIfHigherVersionAvailableTagIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        autoAcquireFreeAppIfHigherVersionAvailableTag_;  if (!tmp.isModifiable()) {
      autoAcquireFreeAppIfHigherVersionAvailableTag_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
   * @param index The index to set the value at.
   * @param value The autoAcquireFreeAppIfHigherVersionAvailableTag to set.
   */
  private void setAutoAcquireFreeAppIfHigherVersionAvailableTag(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureAutoAcquireFreeAppIfHigherVersionAvailableTagIsMutable();
    autoAcquireFreeAppIfHigherVersionAvailableTag_.set(index, value);
  }
  /**
   * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
   * @param value The autoAcquireFreeAppIfHigherVersionAvailableTag to add.
   */
  private void addAutoAcquireFreeAppIfHigherVersionAvailableTag(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureAutoAcquireFreeAppIfHigherVersionAvailableTagIsMutable();
    autoAcquireFreeAppIfHigherVersionAvailableTag_.add(value);
  }
  /**
   * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
   * @param values The autoAcquireFreeAppIfHigherVersionAvailableTag to add.
   */
  private void addAllAutoAcquireFreeAppIfHigherVersionAvailableTag(
      java.lang.Iterable<java.lang.String> values) {
    ensureAutoAcquireFreeAppIfHigherVersionAvailableTagIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, autoAcquireFreeAppIfHigherVersionAvailableTag_);
  }
  /**
   * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
   */
  private void clearAutoAcquireFreeAppIfHigherVersionAvailableTag() {
    autoAcquireFreeAppIfHigherVersionAvailableTag_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
   * @param value The bytes of the autoAcquireFreeAppIfHigherVersionAvailableTag to add.
   */
  private void addAutoAcquireFreeAppIfHigherVersionAvailableTagBytes(
      com.google.protobuf.ByteString value) {
    ensureAutoAcquireFreeAppIfHigherVersionAvailableTagIsMutable();
    autoAcquireFreeAppIfHigherVersionAvailableTag_.add(value.toStringUtf8());
  }

  public static finsky.protos.LibraryReplicationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.LibraryReplicationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.LibraryReplicationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.LibraryReplicationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.LibraryReplicationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.LibraryReplicationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.LibraryReplicationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.LibraryReplicationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.LibraryReplicationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.LibraryReplicationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.LibraryReplicationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.LibraryReplicationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.LibraryReplicationResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.LibraryReplicationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.LibraryReplicationResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.LibraryReplicationResponse)
      finsky.protos.LibraryReplicationResponseOrBuilder {
    // Construct using finsky.protos.LibraryReplicationResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    @java.lang.Override
    public java.util.List<finsky.protos.LibraryUpdateProto.LibraryUpdate> getUpdateList() {
      return java.util.Collections.unmodifiableList(
          instance.getUpdateList());
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    @java.lang.Override
    public int getUpdateCount() {
      return instance.getUpdateCount();
    }/**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    @java.lang.Override
    public finsky.protos.LibraryUpdateProto.LibraryUpdate getUpdate(int index) {
      return instance.getUpdate(index);
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    public Builder setUpdate(
        int index, finsky.protos.LibraryUpdateProto.LibraryUpdate value) {
      copyOnWrite();
      instance.setUpdate(index, value);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    public Builder setUpdate(
        int index, finsky.protos.LibraryUpdateProto.LibraryUpdate.Builder builderForValue) {
      copyOnWrite();
      instance.setUpdate(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    public Builder addUpdate(finsky.protos.LibraryUpdateProto.LibraryUpdate value) {
      copyOnWrite();
      instance.addUpdate(value);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    public Builder addUpdate(
        int index, finsky.protos.LibraryUpdateProto.LibraryUpdate value) {
      copyOnWrite();
      instance.addUpdate(index, value);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    public Builder addUpdate(
        finsky.protos.LibraryUpdateProto.LibraryUpdate.Builder builderForValue) {
      copyOnWrite();
      instance.addUpdate(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    public Builder addUpdate(
        int index, finsky.protos.LibraryUpdateProto.LibraryUpdate.Builder builderForValue) {
      copyOnWrite();
      instance.addUpdate(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    public Builder addAllUpdate(
        java.lang.Iterable<? extends finsky.protos.LibraryUpdateProto.LibraryUpdate> values) {
      copyOnWrite();
      instance.addAllUpdate(values);
      return this;
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    public Builder clearUpdate() {
      copyOnWrite();
      instance.clearUpdate();
      return this;
    }
    /**
     * <code>repeated .finsky.protos.LibraryUpdateProto.LibraryUpdate update = 1;</code>
     */
    public Builder removeUpdate(int index) {
      copyOnWrite();
      instance.removeUpdate(index);
      return this;
    }

    /**
     * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
     * @return A list containing the autoAcquireFreeAppIfHigherVersionAvailableTag.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getAutoAcquireFreeAppIfHigherVersionAvailableTagList() {
      return java.util.Collections.unmodifiableList(
          instance.getAutoAcquireFreeAppIfHigherVersionAvailableTagList());
    }
    /**
     * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
     * @return The count of autoAcquireFreeAppIfHigherVersionAvailableTag.
     */
    @java.lang.Override
    public int getAutoAcquireFreeAppIfHigherVersionAvailableTagCount() {
      return instance.getAutoAcquireFreeAppIfHigherVersionAvailableTagCount();
    }
    /**
     * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
     * @param index The index of the element to return.
     * @return The autoAcquireFreeAppIfHigherVersionAvailableTag at the given index.
     */
    @java.lang.Override
    public java.lang.String getAutoAcquireFreeAppIfHigherVersionAvailableTag(int index) {
      return instance.getAutoAcquireFreeAppIfHigherVersionAvailableTag(index);
    }
    /**
     * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the autoAcquireFreeAppIfHigherVersionAvailableTag at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAutoAcquireFreeAppIfHigherVersionAvailableTagBytes(int index) {
      return instance.getAutoAcquireFreeAppIfHigherVersionAvailableTagBytes(index);
    }
    /**
     * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
     * @param index The index to set the value at.
     * @param value The autoAcquireFreeAppIfHigherVersionAvailableTag to set.
     * @return This builder for chaining.
     */
    public Builder setAutoAcquireFreeAppIfHigherVersionAvailableTag(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setAutoAcquireFreeAppIfHigherVersionAvailableTag(index, value);
      return this;
    }
    /**
     * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
     * @param value The autoAcquireFreeAppIfHigherVersionAvailableTag to add.
     * @return This builder for chaining.
     */
    public Builder addAutoAcquireFreeAppIfHigherVersionAvailableTag(
        java.lang.String value) {
      copyOnWrite();
      instance.addAutoAcquireFreeAppIfHigherVersionAvailableTag(value);
      return this;
    }
    /**
     * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
     * @param values The autoAcquireFreeAppIfHigherVersionAvailableTag to add.
     * @return This builder for chaining.
     */
    public Builder addAllAutoAcquireFreeAppIfHigherVersionAvailableTag(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllAutoAcquireFreeAppIfHigherVersionAvailableTag(values);
      return this;
    }
    /**
     * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoAcquireFreeAppIfHigherVersionAvailableTag() {
      copyOnWrite();
      instance.clearAutoAcquireFreeAppIfHigherVersionAvailableTag();
      return this;
    }
    /**
     * <code>repeated string autoAcquireFreeAppIfHigherVersionAvailableTag = 2;</code>
     * @param value The bytes of the autoAcquireFreeAppIfHigherVersionAvailableTag to add.
     * @return This builder for chaining.
     */
    public Builder addAutoAcquireFreeAppIfHigherVersionAvailableTagBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addAutoAcquireFreeAppIfHigherVersionAvailableTagBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.LibraryReplicationResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.LibraryReplicationResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "update_",
            finsky.protos.LibraryUpdateProto.LibraryUpdate.class,
            "autoAcquireFreeAppIfHigherVersionAvailableTag_",
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0002\u0000\u0001\u001b\u0002\u001a" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.LibraryReplicationResponse> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.LibraryReplicationResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.LibraryReplicationResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.LibraryReplicationResponse)
  private static final finsky.protos.LibraryReplicationResponse DEFAULT_INSTANCE;
  static {
    LibraryReplicationResponse defaultInstance = new LibraryReplicationResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LibraryReplicationResponse.class, defaultInstance);
  }

  public static finsky.protos.LibraryReplicationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LibraryReplicationResponse> PARSER;

  public static com.google.protobuf.Parser<LibraryReplicationResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

