// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.ListResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .finsky.protos.Bucket bucket = 1;</code>
   */
  java.util.List<finsky.protos.Bucket> 
      getBucketList();
  /**
   * <code>repeated .finsky.protos.Bucket bucket = 1;</code>
   */
  finsky.protos.Bucket getBucket(int index);
  /**
   * <code>repeated .finsky.protos.Bucket bucket = 1;</code>
   */
  int getBucketCount();

  /**
   * <code>repeated .finsky.protos.DocV2 doc = 2;</code>
   */
  java.util.List<finsky.protos.DocV2> 
      getDocList();
  /**
   * <code>repeated .finsky.protos.DocV2 doc = 2;</code>
   */
  finsky.protos.DocV2 getDoc(int index);
  /**
   * <code>repeated .finsky.protos.DocV2 doc = 2;</code>
   */
  int getDocCount();
}
