// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.Payload}
 */
public  final class Payload extends
    com.google.protobuf.GeneratedMessageLite<
        Payload, Payload.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.Payload)
    PayloadOrBuilder {
  private Payload() {
  }
  private int bitField0_;
  public static final int LISTRESPONSE_FIELD_NUMBER = 1;
  private finsky.protos.ListResponse listResponse_;
  /**
   * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
   */
  @java.lang.Override
  public boolean hasListResponse() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
   */
  @java.lang.Override
  public finsky.protos.ListResponse getListResponse() {
    return listResponse_ == null ? finsky.protos.ListResponse.getDefaultInstance() : listResponse_;
  }
  /**
   * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
   */
  private void setListResponse(finsky.protos.ListResponse value) {
    value.getClass();
  listResponse_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeListResponse(finsky.protos.ListResponse value) {
    value.getClass();
  if (listResponse_ != null &&
        listResponse_ != finsky.protos.ListResponse.getDefaultInstance()) {
      listResponse_ =
        finsky.protos.ListResponse.newBuilder(listResponse_).mergeFrom(value).buildPartial();
    } else {
      listResponse_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
   */
  private void clearListResponse() {  listResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int DETAILSRESPONSE_FIELD_NUMBER = 2;
  private finsky.protos.Details.DetailsResponse detailsResponse_;
  /**
   * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
   */
  @java.lang.Override
  public boolean hasDetailsResponse() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
   */
  @java.lang.Override
  public finsky.protos.Details.DetailsResponse getDetailsResponse() {
    return detailsResponse_ == null ? finsky.protos.Details.DetailsResponse.getDefaultInstance() : detailsResponse_;
  }
  /**
   * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
   */
  private void setDetailsResponse(finsky.protos.Details.DetailsResponse value) {
    value.getClass();
  detailsResponse_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDetailsResponse(finsky.protos.Details.DetailsResponse value) {
    value.getClass();
  if (detailsResponse_ != null &&
        detailsResponse_ != finsky.protos.Details.DetailsResponse.getDefaultInstance()) {
      detailsResponse_ =
        finsky.protos.Details.DetailsResponse.newBuilder(detailsResponse_).mergeFrom(value).buildPartial();
    } else {
      detailsResponse_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
   */
  private void clearDetailsResponse() {  detailsResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int SEARCHRESPONSE_FIELD_NUMBER = 5;
  private finsky.protos.Search.SearchResponse searchResponse_;
  /**
   * <pre>
   *        optional ReviewResponse reviewResponse = 3;
   *        optional BuyResponse buyResponse = 4;
   * </pre>
   *
   * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
   */
  @java.lang.Override
  public boolean hasSearchResponse() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   *        optional ReviewResponse reviewResponse = 3;
   *        optional BuyResponse buyResponse = 4;
   * </pre>
   *
   * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
   */
  @java.lang.Override
  public finsky.protos.Search.SearchResponse getSearchResponse() {
    return searchResponse_ == null ? finsky.protos.Search.SearchResponse.getDefaultInstance() : searchResponse_;
  }
  /**
   * <pre>
   *        optional ReviewResponse reviewResponse = 3;
   *        optional BuyResponse buyResponse = 4;
   * </pre>
   *
   * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
   */
  private void setSearchResponse(finsky.protos.Search.SearchResponse value) {
    value.getClass();
  searchResponse_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <pre>
   *        optional ReviewResponse reviewResponse = 3;
   *        optional BuyResponse buyResponse = 4;
   * </pre>
   *
   * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSearchResponse(finsky.protos.Search.SearchResponse value) {
    value.getClass();
  if (searchResponse_ != null &&
        searchResponse_ != finsky.protos.Search.SearchResponse.getDefaultInstance()) {
      searchResponse_ =
        finsky.protos.Search.SearchResponse.newBuilder(searchResponse_).mergeFrom(value).buildPartial();
    } else {
      searchResponse_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <pre>
   *        optional ReviewResponse reviewResponse = 3;
   *        optional BuyResponse buyResponse = 4;
   * </pre>
   *
   * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
   */
  private void clearSearchResponse() {  searchResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int BULKDETAILSRESPONSE_FIELD_NUMBER = 19;
  private finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse_;
  /**
   * <pre>
   *        optional BrowseResponse browseResponse = 7;
   *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
   * </pre>
   *
   * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  @java.lang.Override
  public boolean hasBulkDetailsResponse() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   *        optional BrowseResponse browseResponse = 7;
   *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
   * </pre>
   *
   * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  @java.lang.Override
  public finsky.protos.Details.BulkDetailsResponse getBulkDetailsResponse() {
    return bulkDetailsResponse_ == null ? finsky.protos.Details.BulkDetailsResponse.getDefaultInstance() : bulkDetailsResponse_;
  }
  /**
   * <pre>
   *        optional BrowseResponse browseResponse = 7;
   *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
   * </pre>
   *
   * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  private void setBulkDetailsResponse(finsky.protos.Details.BulkDetailsResponse value) {
    value.getClass();
  bulkDetailsResponse_ = value;
    bitField0_ |= 0x00000008;
    }
  /**
   * <pre>
   *        optional BrowseResponse browseResponse = 7;
   *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
   * </pre>
   *
   * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeBulkDetailsResponse(finsky.protos.Details.BulkDetailsResponse value) {
    value.getClass();
  if (bulkDetailsResponse_ != null &&
        bulkDetailsResponse_ != finsky.protos.Details.BulkDetailsResponse.getDefaultInstance()) {
      bulkDetailsResponse_ =
        finsky.protos.Details.BulkDetailsResponse.newBuilder(bulkDetailsResponse_).mergeFrom(value).buildPartial();
    } else {
      bulkDetailsResponse_ = value;
    }
    bitField0_ |= 0x00000008;
  }
  /**
   * <pre>
   *        optional BrowseResponse browseResponse = 7;
   *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
   * </pre>
   *
   * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  private void clearBulkDetailsResponse() {  bulkDetailsResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000008);
  }

  public static final int TESTINGPROGRAMRESPONSE_FIELD_NUMBER = 80;
  private finsky.protos.TestingProgramResponse testingProgramResponse_;
  /**
   * <pre>
   *        optional DeliveryResponse deliveryResponse = 21;
   *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
   *        optional AndroidCheckinResponse androidCheckinResponse = 26;
   *        optional SearchSuggestResponse searchSuggestResponse = 40;
   * </pre>
   *
   * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
   */
  @java.lang.Override
  public boolean hasTestingProgramResponse() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   *        optional DeliveryResponse deliveryResponse = 21;
   *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
   *        optional AndroidCheckinResponse androidCheckinResponse = 26;
   *        optional SearchSuggestResponse searchSuggestResponse = 40;
   * </pre>
   *
   * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
   */
  @java.lang.Override
  public finsky.protos.TestingProgramResponse getTestingProgramResponse() {
    return testingProgramResponse_ == null ? finsky.protos.TestingProgramResponse.getDefaultInstance() : testingProgramResponse_;
  }
  /**
   * <pre>
   *        optional DeliveryResponse deliveryResponse = 21;
   *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
   *        optional AndroidCheckinResponse androidCheckinResponse = 26;
   *        optional SearchSuggestResponse searchSuggestResponse = 40;
   * </pre>
   *
   * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
   */
  private void setTestingProgramResponse(finsky.protos.TestingProgramResponse value) {
    value.getClass();
  testingProgramResponse_ = value;
    bitField0_ |= 0x00000010;
    }
  /**
   * <pre>
   *        optional DeliveryResponse deliveryResponse = 21;
   *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
   *        optional AndroidCheckinResponse androidCheckinResponse = 26;
   *        optional SearchSuggestResponse searchSuggestResponse = 40;
   * </pre>
   *
   * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeTestingProgramResponse(finsky.protos.TestingProgramResponse value) {
    value.getClass();
  if (testingProgramResponse_ != null &&
        testingProgramResponse_ != finsky.protos.TestingProgramResponse.getDefaultInstance()) {
      testingProgramResponse_ =
        finsky.protos.TestingProgramResponse.newBuilder(testingProgramResponse_).mergeFrom(value).buildPartial();
    } else {
      testingProgramResponse_ = value;
    }
    bitField0_ |= 0x00000010;
  }
  /**
   * <pre>
   *        optional DeliveryResponse deliveryResponse = 21;
   *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
   *        optional AndroidCheckinResponse androidCheckinResponse = 26;
   *        optional SearchSuggestResponse searchSuggestResponse = 40;
   * </pre>
   *
   * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
   */
  private void clearTestingProgramResponse() {  testingProgramResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000010);
  }

  public static finsky.protos.Payload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.Payload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.Payload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.Payload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.Payload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.Payload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.Payload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.Payload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.Payload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.Payload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.Payload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.Payload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.Payload prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.Payload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.Payload, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.Payload)
      finsky.protos.PayloadOrBuilder {
    // Construct using finsky.protos.Payload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
     */
    @java.lang.Override
    public boolean hasListResponse() {
      return instance.hasListResponse();
    }
    /**
     * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
     */
    @java.lang.Override
    public finsky.protos.ListResponse getListResponse() {
      return instance.getListResponse();
    }
    /**
     * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
     */
    public Builder setListResponse(finsky.protos.ListResponse value) {
      copyOnWrite();
      instance.setListResponse(value);
      return this;
      }
    /**
     * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
     */
    public Builder setListResponse(
        finsky.protos.ListResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setListResponse(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
     */
    public Builder mergeListResponse(finsky.protos.ListResponse value) {
      copyOnWrite();
      instance.mergeListResponse(value);
      return this;
    }
    /**
     * <code>optional .finsky.protos.ListResponse listResponse = 1;</code>
     */
    public Builder clearListResponse() {  copyOnWrite();
      instance.clearListResponse();
      return this;
    }

    /**
     * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
     */
    @java.lang.Override
    public boolean hasDetailsResponse() {
      return instance.hasDetailsResponse();
    }
    /**
     * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
     */
    @java.lang.Override
    public finsky.protos.Details.DetailsResponse getDetailsResponse() {
      return instance.getDetailsResponse();
    }
    /**
     * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
     */
    public Builder setDetailsResponse(finsky.protos.Details.DetailsResponse value) {
      copyOnWrite();
      instance.setDetailsResponse(value);
      return this;
      }
    /**
     * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
     */
    public Builder setDetailsResponse(
        finsky.protos.Details.DetailsResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setDetailsResponse(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
     */
    public Builder mergeDetailsResponse(finsky.protos.Details.DetailsResponse value) {
      copyOnWrite();
      instance.mergeDetailsResponse(value);
      return this;
    }
    /**
     * <code>optional .finsky.protos.Details.DetailsResponse detailsResponse = 2;</code>
     */
    public Builder clearDetailsResponse() {  copyOnWrite();
      instance.clearDetailsResponse();
      return this;
    }

    /**
     * <pre>
     *        optional ReviewResponse reviewResponse = 3;
     *        optional BuyResponse buyResponse = 4;
     * </pre>
     *
     * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
     */
    @java.lang.Override
    public boolean hasSearchResponse() {
      return instance.hasSearchResponse();
    }
    /**
     * <pre>
     *        optional ReviewResponse reviewResponse = 3;
     *        optional BuyResponse buyResponse = 4;
     * </pre>
     *
     * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
     */
    @java.lang.Override
    public finsky.protos.Search.SearchResponse getSearchResponse() {
      return instance.getSearchResponse();
    }
    /**
     * <pre>
     *        optional ReviewResponse reviewResponse = 3;
     *        optional BuyResponse buyResponse = 4;
     * </pre>
     *
     * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
     */
    public Builder setSearchResponse(finsky.protos.Search.SearchResponse value) {
      copyOnWrite();
      instance.setSearchResponse(value);
      return this;
      }
    /**
     * <pre>
     *        optional ReviewResponse reviewResponse = 3;
     *        optional BuyResponse buyResponse = 4;
     * </pre>
     *
     * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
     */
    public Builder setSearchResponse(
        finsky.protos.Search.SearchResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setSearchResponse(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     *        optional ReviewResponse reviewResponse = 3;
     *        optional BuyResponse buyResponse = 4;
     * </pre>
     *
     * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
     */
    public Builder mergeSearchResponse(finsky.protos.Search.SearchResponse value) {
      copyOnWrite();
      instance.mergeSearchResponse(value);
      return this;
    }
    /**
     * <pre>
     *        optional ReviewResponse reviewResponse = 3;
     *        optional BuyResponse buyResponse = 4;
     * </pre>
     *
     * <code>optional .finsky.protos.Search.SearchResponse searchResponse = 5;</code>
     */
    public Builder clearSearchResponse() {  copyOnWrite();
      instance.clearSearchResponse();
      return this;
    }

    /**
     * <pre>
     *        optional BrowseResponse browseResponse = 7;
     *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
     * </pre>
     *
     * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    @java.lang.Override
    public boolean hasBulkDetailsResponse() {
      return instance.hasBulkDetailsResponse();
    }
    /**
     * <pre>
     *        optional BrowseResponse browseResponse = 7;
     *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
     * </pre>
     *
     * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    @java.lang.Override
    public finsky.protos.Details.BulkDetailsResponse getBulkDetailsResponse() {
      return instance.getBulkDetailsResponse();
    }
    /**
     * <pre>
     *        optional BrowseResponse browseResponse = 7;
     *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
     * </pre>
     *
     * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public Builder setBulkDetailsResponse(finsky.protos.Details.BulkDetailsResponse value) {
      copyOnWrite();
      instance.setBulkDetailsResponse(value);
      return this;
      }
    /**
     * <pre>
     *        optional BrowseResponse browseResponse = 7;
     *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
     * </pre>
     *
     * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public Builder setBulkDetailsResponse(
        finsky.protos.Details.BulkDetailsResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setBulkDetailsResponse(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     *        optional BrowseResponse browseResponse = 7;
     *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
     * </pre>
     *
     * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public Builder mergeBulkDetailsResponse(finsky.protos.Details.BulkDetailsResponse value) {
      copyOnWrite();
      instance.mergeBulkDetailsResponse(value);
      return this;
    }
    /**
     * <pre>
     *        optional BrowseResponse browseResponse = 7;
     *        optional PurchaseStatusResponse purchaseStatusResponse = 8;
     * </pre>
     *
     * <code>optional .finsky.protos.Details.BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public Builder clearBulkDetailsResponse() {  copyOnWrite();
      instance.clearBulkDetailsResponse();
      return this;
    }

    /**
     * <pre>
     *        optional DeliveryResponse deliveryResponse = 21;
     *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
     *        optional AndroidCheckinResponse androidCheckinResponse = 26;
     *        optional SearchSuggestResponse searchSuggestResponse = 40;
     * </pre>
     *
     * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
     */
    @java.lang.Override
    public boolean hasTestingProgramResponse() {
      return instance.hasTestingProgramResponse();
    }
    /**
     * <pre>
     *        optional DeliveryResponse deliveryResponse = 21;
     *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
     *        optional AndroidCheckinResponse androidCheckinResponse = 26;
     *        optional SearchSuggestResponse searchSuggestResponse = 40;
     * </pre>
     *
     * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
     */
    @java.lang.Override
    public finsky.protos.TestingProgramResponse getTestingProgramResponse() {
      return instance.getTestingProgramResponse();
    }
    /**
     * <pre>
     *        optional DeliveryResponse deliveryResponse = 21;
     *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
     *        optional AndroidCheckinResponse androidCheckinResponse = 26;
     *        optional SearchSuggestResponse searchSuggestResponse = 40;
     * </pre>
     *
     * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public Builder setTestingProgramResponse(finsky.protos.TestingProgramResponse value) {
      copyOnWrite();
      instance.setTestingProgramResponse(value);
      return this;
      }
    /**
     * <pre>
     *        optional DeliveryResponse deliveryResponse = 21;
     *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
     *        optional AndroidCheckinResponse androidCheckinResponse = 26;
     *        optional SearchSuggestResponse searchSuggestResponse = 40;
     * </pre>
     *
     * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public Builder setTestingProgramResponse(
        finsky.protos.TestingProgramResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setTestingProgramResponse(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     *        optional DeliveryResponse deliveryResponse = 21;
     *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
     *        optional AndroidCheckinResponse androidCheckinResponse = 26;
     *        optional SearchSuggestResponse searchSuggestResponse = 40;
     * </pre>
     *
     * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public Builder mergeTestingProgramResponse(finsky.protos.TestingProgramResponse value) {
      copyOnWrite();
      instance.mergeTestingProgramResponse(value);
      return this;
    }
    /**
     * <pre>
     *        optional DeliveryResponse deliveryResponse = 21;
     *        optional UploadDeviceConfigResponse uploadDeviceConfigResponse = 25;
     *        optional AndroidCheckinResponse androidCheckinResponse = 26;
     *        optional SearchSuggestResponse searchSuggestResponse = 40;
     * </pre>
     *
     * <code>optional .finsky.protos.TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public Builder clearTestingProgramResponse() {  copyOnWrite();
      instance.clearTestingProgramResponse();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.Payload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.Payload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "listResponse_",
            "detailsResponse_",
            "searchResponse_",
            "bulkDetailsResponse_",
            "testingProgramResponse_",
          };
          java.lang.String info =
              "\u0001\u0005\u0000\u0001\u0001P\u0005\u0000\u0000\u0000\u0001\u1009\u0000\u0002\u1009" +
              "\u0001\u0005\u1009\u0002\u0013\u1009\u0003P\u1009\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.Payload> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.Payload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.Payload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.Payload)
  private static final finsky.protos.Payload DEFAULT_INSTANCE;
  static {
    Payload defaultInstance = new Payload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Payload.class, defaultInstance);
  }

  public static finsky.protos.Payload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Payload> PARSER;

  public static com.google.protobuf.Parser<Payload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

