// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

public interface PublisherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.Publisher)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .finsky.protos.PublisherStream publisherStream = 2;</code>
   * @return Whether the publisherStream field is set.
   */
  boolean hasPublisherStream();
  /**
   * <code>optional .finsky.protos.PublisherStream publisherStream = 2;</code>
   * @return The publisherStream.
   */
  finsky.protos.PublisherStream getPublisherStream();
}
