// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.PublisherStream}
 */
public  final class PublisherStream extends
    com.google.protobuf.GeneratedMessageLite<
        PublisherStream, PublisherStream.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.PublisherStream)
    PublisherStreamOrBuilder {
  private PublisherStream() {
    moreUrl_ = "";
    query_ = "";
  }
  private int bitField0_;
  public static final int MOREURL_FIELD_NUMBER = 3;
  private java.lang.String moreUrl_;
  /**
   * <code>optional string moreUrl = 3;</code>
   * @return Whether the moreUrl field is set.
   */
  @java.lang.Override
  public boolean hasMoreUrl() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string moreUrl = 3;</code>
   * @return The moreUrl.
   */
  @java.lang.Override
  public java.lang.String getMoreUrl() {
    return moreUrl_;
  }
  /**
   * <code>optional string moreUrl = 3;</code>
   * @return The bytes for moreUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMoreUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(moreUrl_);
  }
  /**
   * <code>optional string moreUrl = 3;</code>
   * @param value The moreUrl to set.
   */
  private void setMoreUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    moreUrl_ = value;
  }
  /**
   * <code>optional string moreUrl = 3;</code>
   */
  private void clearMoreUrl() {
    bitField0_ = (bitField0_ & ~0x00000001);
    moreUrl_ = getDefaultInstance().getMoreUrl();
  }
  /**
   * <code>optional string moreUrl = 3;</code>
   * @param value The bytes for moreUrl to set.
   */
  private void setMoreUrlBytes(
      com.google.protobuf.ByteString value) {
    moreUrl_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int QUERY_FIELD_NUMBER = 11;
  private java.lang.String query_;
  /**
   * <code>optional string query = 11;</code>
   * @return Whether the query field is set.
   */
  @java.lang.Override
  public boolean hasQuery() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string query = 11;</code>
   * @return The query.
   */
  @java.lang.Override
  public java.lang.String getQuery() {
    return query_;
  }
  /**
   * <code>optional string query = 11;</code>
   * @return The bytes for query.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(query_);
  }
  /**
   * <code>optional string query = 11;</code>
   * @param value The query to set.
   */
  private void setQuery(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
    query_ = value;
  }
  /**
   * <code>optional string query = 11;</code>
   */
  private void clearQuery() {
    bitField0_ = (bitField0_ & ~0x00000002);
    query_ = getDefaultInstance().getQuery();
  }
  /**
   * <code>optional string query = 11;</code>
   * @param value The bytes for query to set.
   */
  private void setQueryBytes(
      com.google.protobuf.ByteString value) {
    query_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static finsky.protos.PublisherStream parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.PublisherStream parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.PublisherStream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.PublisherStream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.PublisherStream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.PublisherStream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.PublisherStream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.PublisherStream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.PublisherStream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.PublisherStream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.PublisherStream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.PublisherStream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.PublisherStream prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.PublisherStream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.PublisherStream, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.PublisherStream)
      finsky.protos.PublisherStreamOrBuilder {
    // Construct using finsky.protos.PublisherStream.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string moreUrl = 3;</code>
     * @return Whether the moreUrl field is set.
     */
    @java.lang.Override
    public boolean hasMoreUrl() {
      return instance.hasMoreUrl();
    }
    /**
     * <code>optional string moreUrl = 3;</code>
     * @return The moreUrl.
     */
    @java.lang.Override
    public java.lang.String getMoreUrl() {
      return instance.getMoreUrl();
    }
    /**
     * <code>optional string moreUrl = 3;</code>
     * @return The bytes for moreUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMoreUrlBytes() {
      return instance.getMoreUrlBytes();
    }
    /**
     * <code>optional string moreUrl = 3;</code>
     * @param value The moreUrl to set.
     * @return This builder for chaining.
     */
    public Builder setMoreUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setMoreUrl(value);
      return this;
    }
    /**
     * <code>optional string moreUrl = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoreUrl() {
      copyOnWrite();
      instance.clearMoreUrl();
      return this;
    }
    /**
     * <code>optional string moreUrl = 3;</code>
     * @param value The bytes for moreUrl to set.
     * @return This builder for chaining.
     */
    public Builder setMoreUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMoreUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string query = 11;</code>
     * @return Whether the query field is set.
     */
    @java.lang.Override
    public boolean hasQuery() {
      return instance.hasQuery();
    }
    /**
     * <code>optional string query = 11;</code>
     * @return The query.
     */
    @java.lang.Override
    public java.lang.String getQuery() {
      return instance.getQuery();
    }
    /**
     * <code>optional string query = 11;</code>
     * @return The bytes for query.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueryBytes() {
      return instance.getQueryBytes();
    }
    /**
     * <code>optional string query = 11;</code>
     * @param value The query to set.
     * @return This builder for chaining.
     */
    public Builder setQuery(
        java.lang.String value) {
      copyOnWrite();
      instance.setQuery(value);
      return this;
    }
    /**
     * <code>optional string query = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuery() {
      copyOnWrite();
      instance.clearQuery();
      return this;
    }
    /**
     * <code>optional string query = 11;</code>
     * @param value The bytes for query to set.
     * @return This builder for chaining.
     */
    public Builder setQueryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setQueryBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.PublisherStream)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.PublisherStream();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "moreUrl_",
            "query_",
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0003\u000b\u0002\u0000\u0000\u0000\u0003\u1008\u0000\u000b" +
              "\u1008\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.PublisherStream> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.PublisherStream.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.PublisherStream>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.PublisherStream)
  private static final finsky.protos.PublisherStream DEFAULT_INSTANCE;
  static {
    PublisherStream defaultInstance = new PublisherStream();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PublisherStream.class, defaultInstance);
  }

  public static finsky.protos.PublisherStream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PublisherStream> PARSER;

  public static com.google.protobuf.Parser<PublisherStream> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

