// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

public interface RelatedLinksOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.RelatedLinks)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .finsky.protos.RelatedLinksUnknown1 unknown1 = 10;</code>
   * @return Whether the unknown1 field is set.
   */
  boolean hasUnknown1();
  /**
   * <code>optional .finsky.protos.RelatedLinksUnknown1 unknown1 = 10;</code>
   * @return The unknown1.
   */
  finsky.protos.RelatedLinksUnknown1 getUnknown1();

  /**
   * <code>optional string privacyPolicyUrl = 18;</code>
   * @return Whether the privacyPolicyUrl field is set.
   */
  boolean hasPrivacyPolicyUrl();
  /**
   * <code>optional string privacyPolicyUrl = 18;</code>
   * @return The privacyPolicyUrl.
   */
  java.lang.String getPrivacyPolicyUrl();
  /**
   * <code>optional string privacyPolicyUrl = 18;</code>
   * @return The bytes for privacyPolicyUrl.
   */
  com.google.protobuf.ByteString
      getPrivacyPolicyUrlBytes();

  /**
   * <code>optional .finsky.protos.RelatedLink youMightAlsoLike = 24;</code>
   * @return Whether the youMightAlsoLike field is set.
   */
  boolean hasYouMightAlsoLike();
  /**
   * <code>optional .finsky.protos.RelatedLink youMightAlsoLike = 24;</code>
   * @return The youMightAlsoLike.
   */
  finsky.protos.RelatedLink getYouMightAlsoLike();

  /**
   * <code>optional .finsky.protos.Rated rated = 29;</code>
   * @return Whether the rated field is set.
   */
  boolean hasRated();
  /**
   * <code>optional .finsky.protos.Rated rated = 29;</code>
   * @return The rated.
   */
  finsky.protos.Rated getRated();

  /**
   * <code>repeated .finsky.protos.RelatedLink relatedLinks = 34;</code>
   */
  java.util.List<finsky.protos.RelatedLink> 
      getRelatedLinksList();
  /**
   * <code>repeated .finsky.protos.RelatedLink relatedLinks = 34;</code>
   */
  finsky.protos.RelatedLink getRelatedLinks(int index);
  /**
   * <code>repeated .finsky.protos.RelatedLink relatedLinks = 34;</code>
   */
  int getRelatedLinksCount();

  /**
   * <code>optional .finsky.protos.CategoryInfo categoryInfo = 53;</code>
   * @return Whether the categoryInfo field is set.
   */
  boolean hasCategoryInfo();
  /**
   * <code>optional .finsky.protos.CategoryInfo categoryInfo = 53;</code>
   * @return The categoryInfo.
   */
  finsky.protos.CategoryInfo getCategoryInfo();
}
