// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.RelatedLink}
 */
public  final class RelatedLink extends
    com.google.protobuf.GeneratedMessageLite<
        RelatedLink, RelatedLink.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.RelatedLink)
    RelatedLinkOrBuilder {
  private RelatedLink() {
    label_ = "";
    url1_ = "";
    url2_ = "";
  }
  private int bitField0_;
  public static final int LABEL_FIELD_NUMBER = 1;
  private java.lang.String label_;
  /**
   * <code>optional string label = 1;</code>
   * @return Whether the label field is set.
   */
  @java.lang.Override
  public boolean hasLabel() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string label = 1;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    return label_;
  }
  /**
   * <code>optional string label = 1;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(label_);
  }
  /**
   * <code>optional string label = 1;</code>
   * @param value The label to set.
   */
  private void setLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    label_ = value;
  }
  /**
   * <code>optional string label = 1;</code>
   */
  private void clearLabel() {
    bitField0_ = (bitField0_ & ~0x00000001);
    label_ = getDefaultInstance().getLabel();
  }
  /**
   * <code>optional string label = 1;</code>
   * @param value The bytes for label to set.
   */
  private void setLabelBytes(
      com.google.protobuf.ByteString value) {
    label_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int URL1_FIELD_NUMBER = 2;
  private java.lang.String url1_;
  /**
   * <code>optional string url1 = 2;</code>
   * @return Whether the url1 field is set.
   */
  @java.lang.Override
  public boolean hasUrl1() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string url1 = 2;</code>
   * @return The url1.
   */
  @java.lang.Override
  public java.lang.String getUrl1() {
    return url1_;
  }
  /**
   * <code>optional string url1 = 2;</code>
   * @return The bytes for url1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrl1Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(url1_);
  }
  /**
   * <code>optional string url1 = 2;</code>
   * @param value The url1 to set.
   */
  private void setUrl1(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
    url1_ = value;
  }
  /**
   * <code>optional string url1 = 2;</code>
   */
  private void clearUrl1() {
    bitField0_ = (bitField0_ & ~0x00000002);
    url1_ = getDefaultInstance().getUrl1();
  }
  /**
   * <code>optional string url1 = 2;</code>
   * @param value The bytes for url1 to set.
   */
  private void setUrl1Bytes(
      com.google.protobuf.ByteString value) {
    url1_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static final int URL2_FIELD_NUMBER = 3;
  private java.lang.String url2_;
  /**
   * <code>optional string url2 = 3;</code>
   * @return Whether the url2 field is set.
   */
  @java.lang.Override
  public boolean hasUrl2() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string url2 = 3;</code>
   * @return The url2.
   */
  @java.lang.Override
  public java.lang.String getUrl2() {
    return url2_;
  }
  /**
   * <code>optional string url2 = 3;</code>
   * @return The bytes for url2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrl2Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(url2_);
  }
  /**
   * <code>optional string url2 = 3;</code>
   * @param value The url2 to set.
   */
  private void setUrl2(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
    url2_ = value;
  }
  /**
   * <code>optional string url2 = 3;</code>
   */
  private void clearUrl2() {
    bitField0_ = (bitField0_ & ~0x00000004);
    url2_ = getDefaultInstance().getUrl2();
  }
  /**
   * <code>optional string url2 = 3;</code>
   * @param value The bytes for url2 to set.
   */
  private void setUrl2Bytes(
      com.google.protobuf.ByteString value) {
    url2_ = value.toStringUtf8();
    bitField0_ |= 0x00000004;
  }

  public static finsky.protos.RelatedLink parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.RelatedLink parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.RelatedLink parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.RelatedLink parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.RelatedLink parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.RelatedLink parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.RelatedLink parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.RelatedLink parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.RelatedLink parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.RelatedLink parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.RelatedLink parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.RelatedLink parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.RelatedLink prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.RelatedLink}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.RelatedLink, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.RelatedLink)
      finsky.protos.RelatedLinkOrBuilder {
    // Construct using finsky.protos.RelatedLink.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string label = 1;</code>
     * @return Whether the label field is set.
     */
    @java.lang.Override
    public boolean hasLabel() {
      return instance.hasLabel();
    }
    /**
     * <code>optional string label = 1;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      return instance.getLabel();
    }
    /**
     * <code>optional string label = 1;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      return instance.getLabelBytes();
    }
    /**
     * <code>optional string label = 1;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setLabel(value);
      return this;
    }
    /**
     * <code>optional string label = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      copyOnWrite();
      instance.clearLabel();
      return this;
    }
    /**
     * <code>optional string label = 1;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLabelBytes(value);
      return this;
    }

    /**
     * <code>optional string url1 = 2;</code>
     * @return Whether the url1 field is set.
     */
    @java.lang.Override
    public boolean hasUrl1() {
      return instance.hasUrl1();
    }
    /**
     * <code>optional string url1 = 2;</code>
     * @return The url1.
     */
    @java.lang.Override
    public java.lang.String getUrl1() {
      return instance.getUrl1();
    }
    /**
     * <code>optional string url1 = 2;</code>
     * @return The bytes for url1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrl1Bytes() {
      return instance.getUrl1Bytes();
    }
    /**
     * <code>optional string url1 = 2;</code>
     * @param value The url1 to set.
     * @return This builder for chaining.
     */
    public Builder setUrl1(
        java.lang.String value) {
      copyOnWrite();
      instance.setUrl1(value);
      return this;
    }
    /**
     * <code>optional string url1 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl1() {
      copyOnWrite();
      instance.clearUrl1();
      return this;
    }
    /**
     * <code>optional string url1 = 2;</code>
     * @param value The bytes for url1 to set.
     * @return This builder for chaining.
     */
    public Builder setUrl1Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUrl1Bytes(value);
      return this;
    }

    /**
     * <code>optional string url2 = 3;</code>
     * @return Whether the url2 field is set.
     */
    @java.lang.Override
    public boolean hasUrl2() {
      return instance.hasUrl2();
    }
    /**
     * <code>optional string url2 = 3;</code>
     * @return The url2.
     */
    @java.lang.Override
    public java.lang.String getUrl2() {
      return instance.getUrl2();
    }
    /**
     * <code>optional string url2 = 3;</code>
     * @return The bytes for url2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrl2Bytes() {
      return instance.getUrl2Bytes();
    }
    /**
     * <code>optional string url2 = 3;</code>
     * @param value The url2 to set.
     * @return This builder for chaining.
     */
    public Builder setUrl2(
        java.lang.String value) {
      copyOnWrite();
      instance.setUrl2(value);
      return this;
    }
    /**
     * <code>optional string url2 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl2() {
      copyOnWrite();
      instance.clearUrl2();
      return this;
    }
    /**
     * <code>optional string url2 = 3;</code>
     * @param value The bytes for url2 to set.
     * @return This builder for chaining.
     */
    public Builder setUrl2Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUrl2Bytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.RelatedLink)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.RelatedLink();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "label_",
            "url1_",
            "url2_",
          };
          java.lang.String info =
              "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1008\u0000\u0002" +
              "\u1008\u0001\u0003\u1008\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.RelatedLink> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.RelatedLink.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.RelatedLink>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.RelatedLink)
  private static final finsky.protos.RelatedLink DEFAULT_INSTANCE;
  static {
    RelatedLink defaultInstance = new RelatedLink();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RelatedLink.class, defaultInstance);
  }

  public static finsky.protos.RelatedLink getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RelatedLink> PARSER;

  public static com.google.protobuf.Parser<RelatedLink> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

