// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.RelatedLinksUnknown1}
 */
public  final class RelatedLinksUnknown1 extends
    com.google.protobuf.GeneratedMessageLite<
        RelatedLinksUnknown1, RelatedLinksUnknown1.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.RelatedLinksUnknown1)
    RelatedLinksUnknown1OrBuilder {
  private RelatedLinksUnknown1() {
  }
  private int bitField0_;
  public static final int UNKNOWN2_FIELD_NUMBER = 2;
  private finsky.protos.RelatedLinksUnknown2 unknown2_;
  /**
   * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  @java.lang.Override
  public boolean hasUnknown2() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  @java.lang.Override
  public finsky.protos.RelatedLinksUnknown2 getUnknown2() {
    return unknown2_ == null ? finsky.protos.RelatedLinksUnknown2.getDefaultInstance() : unknown2_;
  }
  /**
   * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  private void setUnknown2(finsky.protos.RelatedLinksUnknown2 value) {
    value.getClass();
  unknown2_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeUnknown2(finsky.protos.RelatedLinksUnknown2 value) {
    value.getClass();
  if (unknown2_ != null &&
        unknown2_ != finsky.protos.RelatedLinksUnknown2.getDefaultInstance()) {
      unknown2_ =
        finsky.protos.RelatedLinksUnknown2.newBuilder(unknown2_).mergeFrom(value).buildPartial();
    } else {
      unknown2_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  private void clearUnknown2() {  unknown2_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static finsky.protos.RelatedLinksUnknown1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.RelatedLinksUnknown1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.RelatedLinksUnknown1 prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.RelatedLinksUnknown1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.RelatedLinksUnknown1, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.RelatedLinksUnknown1)
      finsky.protos.RelatedLinksUnknown1OrBuilder {
    // Construct using finsky.protos.RelatedLinksUnknown1.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    @java.lang.Override
    public boolean hasUnknown2() {
      return instance.hasUnknown2();
    }
    /**
     * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    @java.lang.Override
    public finsky.protos.RelatedLinksUnknown2 getUnknown2() {
      return instance.getUnknown2();
    }
    /**
     * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public Builder setUnknown2(finsky.protos.RelatedLinksUnknown2 value) {
      copyOnWrite();
      instance.setUnknown2(value);
      return this;
      }
    /**
     * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public Builder setUnknown2(
        finsky.protos.RelatedLinksUnknown2.Builder builderForValue) {
      copyOnWrite();
      instance.setUnknown2(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public Builder mergeUnknown2(finsky.protos.RelatedLinksUnknown2 value) {
      copyOnWrite();
      instance.mergeUnknown2(value);
      return this;
    }
    /**
     * <code>optional .finsky.protos.RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public Builder clearUnknown2() {  copyOnWrite();
      instance.clearUnknown2();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.RelatedLinksUnknown1)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.RelatedLinksUnknown1();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "unknown2_",
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0001\u0002\u0002\u0001\u0000\u0000\u0000\u0002\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.RelatedLinksUnknown1> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.RelatedLinksUnknown1.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.RelatedLinksUnknown1>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.RelatedLinksUnknown1)
  private static final finsky.protos.RelatedLinksUnknown1 DEFAULT_INSTANCE;
  static {
    RelatedLinksUnknown1 defaultInstance = new RelatedLinksUnknown1();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RelatedLinksUnknown1.class, defaultInstance);
  }

  public static finsky.protos.RelatedLinksUnknown1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RelatedLinksUnknown1> PARSER;

  public static com.google.protobuf.Parser<RelatedLinksUnknown1> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

