// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.SectionMetaData}
 */
public  final class SectionMetaData extends
    com.google.protobuf.GeneratedMessageLite<
        SectionMetaData, SectionMetaData.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.SectionMetaData)
    SectionMetaDataOrBuilder {
  private SectionMetaData() {
    header_ = "";
    listUrl_ = "";
    browseUrl_ = "";
    description_ = "";
  }
  private int bitField0_;
  public static final int HEADER_FIELD_NUMBER = 1;
  private java.lang.String header_;
  /**
   * <code>optional string header = 1;</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string header = 1;</code>
   * @return The header.
   */
  @java.lang.Override
  public java.lang.String getHeader() {
    return header_;
  }
  /**
   * <code>optional string header = 1;</code>
   * @return The bytes for header.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHeaderBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(header_);
  }
  /**
   * <code>optional string header = 1;</code>
   * @param value The header to set.
   */
  private void setHeader(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    header_ = value;
  }
  /**
   * <code>optional string header = 1;</code>
   */
  private void clearHeader() {
    bitField0_ = (bitField0_ & ~0x00000001);
    header_ = getDefaultInstance().getHeader();
  }
  /**
   * <code>optional string header = 1;</code>
   * @param value The bytes for header to set.
   */
  private void setHeaderBytes(
      com.google.protobuf.ByteString value) {
    header_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int LISTURL_FIELD_NUMBER = 2;
  private java.lang.String listUrl_;
  /**
   * <code>optional string listUrl = 2;</code>
   * @return Whether the listUrl field is set.
   */
  @java.lang.Override
  public boolean hasListUrl() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string listUrl = 2;</code>
   * @return The listUrl.
   */
  @java.lang.Override
  public java.lang.String getListUrl() {
    return listUrl_;
  }
  /**
   * <code>optional string listUrl = 2;</code>
   * @return The bytes for listUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getListUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(listUrl_);
  }
  /**
   * <code>optional string listUrl = 2;</code>
   * @param value The listUrl to set.
   */
  private void setListUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
    listUrl_ = value;
  }
  /**
   * <code>optional string listUrl = 2;</code>
   */
  private void clearListUrl() {
    bitField0_ = (bitField0_ & ~0x00000002);
    listUrl_ = getDefaultInstance().getListUrl();
  }
  /**
   * <code>optional string listUrl = 2;</code>
   * @param value The bytes for listUrl to set.
   */
  private void setListUrlBytes(
      com.google.protobuf.ByteString value) {
    listUrl_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static final int BROWSEURL_FIELD_NUMBER = 3;
  private java.lang.String browseUrl_;
  /**
   * <code>optional string browseUrl = 3;</code>
   * @return Whether the browseUrl field is set.
   */
  @java.lang.Override
  public boolean hasBrowseUrl() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string browseUrl = 3;</code>
   * @return The browseUrl.
   */
  @java.lang.Override
  public java.lang.String getBrowseUrl() {
    return browseUrl_;
  }
  /**
   * <code>optional string browseUrl = 3;</code>
   * @return The bytes for browseUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBrowseUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(browseUrl_);
  }
  /**
   * <code>optional string browseUrl = 3;</code>
   * @param value The browseUrl to set.
   */
  private void setBrowseUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
    browseUrl_ = value;
  }
  /**
   * <code>optional string browseUrl = 3;</code>
   */
  private void clearBrowseUrl() {
    bitField0_ = (bitField0_ & ~0x00000004);
    browseUrl_ = getDefaultInstance().getBrowseUrl();
  }
  /**
   * <code>optional string browseUrl = 3;</code>
   * @param value The bytes for browseUrl to set.
   */
  private void setBrowseUrlBytes(
      com.google.protobuf.ByteString value) {
    browseUrl_ = value.toStringUtf8();
    bitField0_ |= 0x00000004;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private java.lang.String description_;
  /**
   * <code>optional string description = 4;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>optional string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>optional string description = 4;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000008;
    description_ = value;
  }
  /**
   * <code>optional string description = 4;</code>
   */
  private void clearDescription() {
    bitField0_ = (bitField0_ & ~0x00000008);
    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>optional string description = 4;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    description_ = value.toStringUtf8();
    bitField0_ |= 0x00000008;
  }

  public static finsky.protos.SectionMetaData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.SectionMetaData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.SectionMetaData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.SectionMetaData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.SectionMetaData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.SectionMetaData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.SectionMetaData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.SectionMetaData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static finsky.protos.SectionMetaData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static finsky.protos.SectionMetaData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.SectionMetaData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.SectionMetaData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.SectionMetaData prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.SectionMetaData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.SectionMetaData, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.SectionMetaData)
      finsky.protos.SectionMetaDataOrBuilder {
    // Construct using finsky.protos.SectionMetaData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return instance.hasHeader();
    }
    /**
     * <code>optional string header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public java.lang.String getHeader() {
      return instance.getHeader();
    }
    /**
     * <code>optional string header = 1;</code>
     * @return The bytes for header.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeaderBytes() {
      return instance.getHeaderBytes();
    }
    /**
     * <code>optional string header = 1;</code>
     * @param value The header to set.
     * @return This builder for chaining.
     */
    public Builder setHeader(
        java.lang.String value) {
      copyOnWrite();
      instance.setHeader(value);
      return this;
    }
    /**
     * <code>optional string header = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeader() {
      copyOnWrite();
      instance.clearHeader();
      return this;
    }
    /**
     * <code>optional string header = 1;</code>
     * @param value The bytes for header to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHeaderBytes(value);
      return this;
    }

    /**
     * <code>optional string listUrl = 2;</code>
     * @return Whether the listUrl field is set.
     */
    @java.lang.Override
    public boolean hasListUrl() {
      return instance.hasListUrl();
    }
    /**
     * <code>optional string listUrl = 2;</code>
     * @return The listUrl.
     */
    @java.lang.Override
    public java.lang.String getListUrl() {
      return instance.getListUrl();
    }
    /**
     * <code>optional string listUrl = 2;</code>
     * @return The bytes for listUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getListUrlBytes() {
      return instance.getListUrlBytes();
    }
    /**
     * <code>optional string listUrl = 2;</code>
     * @param value The listUrl to set.
     * @return This builder for chaining.
     */
    public Builder setListUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setListUrl(value);
      return this;
    }
    /**
     * <code>optional string listUrl = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearListUrl() {
      copyOnWrite();
      instance.clearListUrl();
      return this;
    }
    /**
     * <code>optional string listUrl = 2;</code>
     * @param value The bytes for listUrl to set.
     * @return This builder for chaining.
     */
    public Builder setListUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setListUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string browseUrl = 3;</code>
     * @return Whether the browseUrl field is set.
     */
    @java.lang.Override
    public boolean hasBrowseUrl() {
      return instance.hasBrowseUrl();
    }
    /**
     * <code>optional string browseUrl = 3;</code>
     * @return The browseUrl.
     */
    @java.lang.Override
    public java.lang.String getBrowseUrl() {
      return instance.getBrowseUrl();
    }
    /**
     * <code>optional string browseUrl = 3;</code>
     * @return The bytes for browseUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrowseUrlBytes() {
      return instance.getBrowseUrlBytes();
    }
    /**
     * <code>optional string browseUrl = 3;</code>
     * @param value The browseUrl to set.
     * @return This builder for chaining.
     */
    public Builder setBrowseUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setBrowseUrl(value);
      return this;
    }
    /**
     * <code>optional string browseUrl = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrowseUrl() {
      copyOnWrite();
      instance.clearBrowseUrl();
      return this;
    }
    /**
     * <code>optional string browseUrl = 3;</code>
     * @param value The bytes for browseUrl to set.
     * @return This builder for chaining.
     */
    public Builder setBrowseUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBrowseUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string description = 4;</code>
     * @return Whether the description field is set.
     */
    @java.lang.Override
    public boolean hasDescription() {
      return instance.hasDescription();
    }
    /**
     * <code>optional string description = 4;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>optional string description = 4;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>optional string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>optional string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>optional string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.SectionMetaData)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.SectionMetaData();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "header_",
            "listUrl_",
            "browseUrl_",
            "description_",
          };
          java.lang.String info =
              "\u0001\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u1008\u0000\u0002" +
              "\u1008\u0001\u0003\u1008\u0002\u0004\u1008\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.SectionMetaData> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.SectionMetaData.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.SectionMetaData>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.SectionMetaData)
  private static final finsky.protos.SectionMetaData DEFAULT_INSTANCE;
  static {
    SectionMetaData defaultInstance = new SectionMetaData();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SectionMetaData.class, defaultInstance);
  }

  public static finsky.protos.SectionMetaData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SectionMetaData> PARSER;

  public static com.google.protobuf.Parser<SectionMetaData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

