// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.SplitDeliveryData}
 */
public  final class SplitDeliveryData extends
    com.google.protobuf.GeneratedMessageLite<
        SplitDeliveryData, SplitDeliveryData.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.SplitDeliveryData)
    SplitDeliveryDataOrBuilder {
  private SplitDeliveryData() {
    name_ = "";
    sha1_ = "";
    downloadUrl_ = "";
    compressedDownloadUrl_ = "";
    sha256_ = "";
  }
  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>optional string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    name_ = value;
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void clearName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>optional string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    name_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int DOWNLOADSIZE_FIELD_NUMBER = 2;
  private long downloadSize_;
  /**
   * <code>optional int64 downloadSize = 2;</code>
   * @return Whether the downloadSize field is set.
   */
  @java.lang.Override
  public boolean hasDownloadSize() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 downloadSize = 2;</code>
   * @return The downloadSize.
   */
  @java.lang.Override
  public long getDownloadSize() {
    return downloadSize_;
  }
  /**
   * <code>optional int64 downloadSize = 2;</code>
   * @param value The downloadSize to set.
   */
  private void setDownloadSize(long value) {
    bitField0_ |= 0x00000002;
    downloadSize_ = value;
  }
  /**
   * <code>optional int64 downloadSize = 2;</code>
   */
  private void clearDownloadSize() {
    bitField0_ = (bitField0_ & ~0x00000002);
    downloadSize_ = 0L;
  }

  public static final int COMPRESSEDSIZE_FIELD_NUMBER = 3;
  private long compressedSize_;
  /**
   * <code>optional int64 compressedSize = 3;</code>
   * @return Whether the compressedSize field is set.
   */
  @java.lang.Override
  public boolean hasCompressedSize() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int64 compressedSize = 3;</code>
   * @return The compressedSize.
   */
  @java.lang.Override
  public long getCompressedSize() {
    return compressedSize_;
  }
  /**
   * <code>optional int64 compressedSize = 3;</code>
   * @param value The compressedSize to set.
   */
  private void setCompressedSize(long value) {
    bitField0_ |= 0x00000004;
    compressedSize_ = value;
  }
  /**
   * <code>optional int64 compressedSize = 3;</code>
   */
  private void clearCompressedSize() {
    bitField0_ = (bitField0_ & ~0x00000004);
    compressedSize_ = 0L;
  }

  public static final int SHA1_FIELD_NUMBER = 4;
  private java.lang.String sha1_;
  /**
   * <code>optional string sha1 = 4;</code>
   * @return Whether the sha1 field is set.
   */
  @java.lang.Override
  public boolean hasSha1() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string sha1 = 4;</code>
   * @return The sha1.
   */
  @java.lang.Override
  public java.lang.String getSha1() {
    return sha1_;
  }
  /**
   * <code>optional string sha1 = 4;</code>
   * @return The bytes for sha1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSha1Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sha1_);
  }
  /**
   * <code>optional string sha1 = 4;</code>
   * @param value The sha1 to set.
   */
  private void setSha1(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000008;
    sha1_ = value;
  }
  /**
   * <code>optional string sha1 = 4;</code>
   */
  private void clearSha1() {
    bitField0_ = (bitField0_ & ~0x00000008);
    sha1_ = getDefaultInstance().getSha1();
  }
  /**
   * <code>optional string sha1 = 4;</code>
   * @param value The bytes for sha1 to set.
   */
  private void setSha1Bytes(
      com.google.protobuf.ByteString value) {
    sha1_ = value.toStringUtf8();
    bitField0_ |= 0x00000008;
  }

  public static final int DOWNLOADURL_FIELD_NUMBER = 5;
  private java.lang.String downloadUrl_;
  /**
   * <code>optional string downloadUrl = 5;</code>
   * @return Whether the downloadUrl field is set.
   */
  @java.lang.Override
  public boolean hasDownloadUrl() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string downloadUrl = 5;</code>
   * @return The downloadUrl.
   */
  @java.lang.Override
  public java.lang.String getDownloadUrl() {
    return downloadUrl_;
  }
  /**
   * <code>optional string downloadUrl = 5;</code>
   * @return The bytes for downloadUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDownloadUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(downloadUrl_);
  }
  /**
   * <code>optional string downloadUrl = 5;</code>
   * @param value The downloadUrl to set.
   */
  private void setDownloadUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000010;
    downloadUrl_ = value;
  }
  /**
   * <code>optional string downloadUrl = 5;</code>
   */
  private void clearDownloadUrl() {
    bitField0_ = (bitField0_ & ~0x00000010);
    downloadUrl_ = getDefaultInstance().getDownloadUrl();
  }
  /**
   * <code>optional string downloadUrl = 5;</code>
   * @param value The bytes for downloadUrl to set.
   */
  private void setDownloadUrlBytes(
      com.google.protobuf.ByteString value) {
    downloadUrl_ = value.toStringUtf8();
    bitField0_ |= 0x00000010;
  }

  public static final int COMPRESSEDDOWNLOADURL_FIELD_NUMBER = 6;
  private java.lang.String compressedDownloadUrl_;
  /**
   * <code>optional string compressedDownloadUrl = 6;</code>
   * @return Whether the compressedDownloadUrl field is set.
   */
  @java.lang.Override
  public boolean hasCompressedDownloadUrl() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string compressedDownloadUrl = 6;</code>
   * @return The compressedDownloadUrl.
   */
  @java.lang.Override
  public java.lang.String getCompressedDownloadUrl() {
    return compressedDownloadUrl_;
  }
  /**
   * <code>optional string compressedDownloadUrl = 6;</code>
   * @return The bytes for compressedDownloadUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompressedDownloadUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(compressedDownloadUrl_);
  }
  /**
   * <code>optional string compressedDownloadUrl = 6;</code>
   * @param value The compressedDownloadUrl to set.
   */
  private void setCompressedDownloadUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000020;
    compressedDownloadUrl_ = value;
  }
  /**
   * <code>optional string compressedDownloadUrl = 6;</code>
   */
  private void clearCompressedDownloadUrl() {
    bitField0_ = (bitField0_ & ~0x00000020);
    compressedDownloadUrl_ = getDefaultInstance().getCompressedDownloadUrl();
  }
  /**
   * <code>optional string compressedDownloadUrl = 6;</code>
   * @param value The bytes for compressedDownloadUrl to set.
   */
  private void setCompressedDownloadUrlBytes(
      com.google.protobuf.ByteString value) {
    compressedDownloadUrl_ = value.toStringUtf8();
    bitField0_ |= 0x00000020;
  }

  public static final int PATCHDATA_FIELD_NUMBER = 7;
  private finsky.protos.AndroidAppPatchData patchData_;
  /**
   * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
   */
  @java.lang.Override
  public boolean hasPatchData() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
   */
  @java.lang.Override
  public finsky.protos.AndroidAppPatchData getPatchData() {
    return patchData_ == null ? finsky.protos.AndroidAppPatchData.getDefaultInstance() : patchData_;
  }
  /**
   * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
   */
  private void setPatchData(finsky.protos.AndroidAppPatchData value) {
    value.getClass();
  patchData_ = value;
    bitField0_ |= 0x00000040;
    }
  /**
   * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergePatchData(finsky.protos.AndroidAppPatchData value) {
    value.getClass();
  if (patchData_ != null &&
        patchData_ != finsky.protos.AndroidAppPatchData.getDefaultInstance()) {
      patchData_ =
        finsky.protos.AndroidAppPatchData.newBuilder(patchData_).mergeFrom(value).buildPartial();
    } else {
      patchData_ = value;
    }
    bitField0_ |= 0x00000040;
  }
  /**
   * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
   */
  private void clearPatchData() {  patchData_ = null;
    bitField0_ = (bitField0_ & ~0x00000040);
  }

  public static final int COMPRESSEDAPPDATA_FIELD_NUMBER = 8;
  private finsky.protos.CompressedAppData compressedAppData_;
  /**
   * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
   */
  @java.lang.Override
  public boolean hasCompressedAppData() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
   */
  @java.lang.Override
  public finsky.protos.CompressedAppData getCompressedAppData() {
    return compressedAppData_ == null ? finsky.protos.CompressedAppData.getDefaultInstance() : compressedAppData_;
  }
  /**
   * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
   */
  private void setCompressedAppData(finsky.protos.CompressedAppData value) {
    value.getClass();
  compressedAppData_ = value;
    bitField0_ |= 0x00000080;
    }
  /**
   * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeCompressedAppData(finsky.protos.CompressedAppData value) {
    value.getClass();
  if (compressedAppData_ != null &&
        compressedAppData_ != finsky.protos.CompressedAppData.getDefaultInstance()) {
      compressedAppData_ =
        finsky.protos.CompressedAppData.newBuilder(compressedAppData_).mergeFrom(value).buildPartial();
    } else {
      compressedAppData_ = value;
    }
    bitField0_ |= 0x00000080;
  }
  /**
   * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
   */
  private void clearCompressedAppData() {  compressedAppData_ = null;
    bitField0_ = (bitField0_ & ~0x00000080);
  }

  public static final int SHA256_FIELD_NUMBER = 9;
  private java.lang.String sha256_;
  /**
   * <code>optional string sha256 = 9;</code>
   * @return Whether the sha256 field is set.
   */
  @java.lang.Override
  public boolean hasSha256() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional string sha256 = 9;</code>
   * @return The sha256.
   */
  @java.lang.Override
  public java.lang.String getSha256() {
    return sha256_;
  }
  /**
   * <code>optional string sha256 = 9;</code>
   * @return The bytes for sha256.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSha256Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sha256_);
  }
  /**
   * <code>optional string sha256 = 9;</code>
   * @param value The sha256 to set.
   */
  private void setSha256(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000100;
    sha256_ = value;
  }
  /**
   * <code>optional string sha256 = 9;</code>
   */
  private void clearSha256() {
    bitField0_ = (bitField0_ & ~0x00000100);
    sha256_ = getDefaultInstance().getSha256();
  }
  /**
   * <code>optional string sha256 = 9;</code>
   * @param value The bytes for sha256 to set.
   */
  private void setSha256Bytes(
      com.google.protobuf.ByteString value) {
    sha256_ = value.toStringUtf8();
    bitField0_ |= 0x00000100;
  }

  public static finsky.protos.SplitDeliveryData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.SplitDeliveryData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.SplitDeliveryData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.SplitDeliveryData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.SplitDeliveryData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.SplitDeliveryData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.SplitDeliveryData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.SplitDeliveryData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.SplitDeliveryData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.SplitDeliveryData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.SplitDeliveryData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.SplitDeliveryData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.SplitDeliveryData prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.SplitDeliveryData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.SplitDeliveryData, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.SplitDeliveryData)
      finsky.protos.SplitDeliveryDataOrBuilder {
    // Construct using finsky.protos.SplitDeliveryData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return instance.hasName();
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>optional int64 downloadSize = 2;</code>
     * @return Whether the downloadSize field is set.
     */
    @java.lang.Override
    public boolean hasDownloadSize() {
      return instance.hasDownloadSize();
    }
    /**
     * <code>optional int64 downloadSize = 2;</code>
     * @return The downloadSize.
     */
    @java.lang.Override
    public long getDownloadSize() {
      return instance.getDownloadSize();
    }
    /**
     * <code>optional int64 downloadSize = 2;</code>
     * @param value The downloadSize to set.
     * @return This builder for chaining.
     */
    public Builder setDownloadSize(long value) {
      copyOnWrite();
      instance.setDownloadSize(value);
      return this;
    }
    /**
     * <code>optional int64 downloadSize = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDownloadSize() {
      copyOnWrite();
      instance.clearDownloadSize();
      return this;
    }

    /**
     * <code>optional int64 compressedSize = 3;</code>
     * @return Whether the compressedSize field is set.
     */
    @java.lang.Override
    public boolean hasCompressedSize() {
      return instance.hasCompressedSize();
    }
    /**
     * <code>optional int64 compressedSize = 3;</code>
     * @return The compressedSize.
     */
    @java.lang.Override
    public long getCompressedSize() {
      return instance.getCompressedSize();
    }
    /**
     * <code>optional int64 compressedSize = 3;</code>
     * @param value The compressedSize to set.
     * @return This builder for chaining.
     */
    public Builder setCompressedSize(long value) {
      copyOnWrite();
      instance.setCompressedSize(value);
      return this;
    }
    /**
     * <code>optional int64 compressedSize = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompressedSize() {
      copyOnWrite();
      instance.clearCompressedSize();
      return this;
    }

    /**
     * <code>optional string sha1 = 4;</code>
     * @return Whether the sha1 field is set.
     */
    @java.lang.Override
    public boolean hasSha1() {
      return instance.hasSha1();
    }
    /**
     * <code>optional string sha1 = 4;</code>
     * @return The sha1.
     */
    @java.lang.Override
    public java.lang.String getSha1() {
      return instance.getSha1();
    }
    /**
     * <code>optional string sha1 = 4;</code>
     * @return The bytes for sha1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSha1Bytes() {
      return instance.getSha1Bytes();
    }
    /**
     * <code>optional string sha1 = 4;</code>
     * @param value The sha1 to set.
     * @return This builder for chaining.
     */
    public Builder setSha1(
        java.lang.String value) {
      copyOnWrite();
      instance.setSha1(value);
      return this;
    }
    /**
     * <code>optional string sha1 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSha1() {
      copyOnWrite();
      instance.clearSha1();
      return this;
    }
    /**
     * <code>optional string sha1 = 4;</code>
     * @param value The bytes for sha1 to set.
     * @return This builder for chaining.
     */
    public Builder setSha1Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSha1Bytes(value);
      return this;
    }

    /**
     * <code>optional string downloadUrl = 5;</code>
     * @return Whether the downloadUrl field is set.
     */
    @java.lang.Override
    public boolean hasDownloadUrl() {
      return instance.hasDownloadUrl();
    }
    /**
     * <code>optional string downloadUrl = 5;</code>
     * @return The downloadUrl.
     */
    @java.lang.Override
    public java.lang.String getDownloadUrl() {
      return instance.getDownloadUrl();
    }
    /**
     * <code>optional string downloadUrl = 5;</code>
     * @return The bytes for downloadUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDownloadUrlBytes() {
      return instance.getDownloadUrlBytes();
    }
    /**
     * <code>optional string downloadUrl = 5;</code>
     * @param value The downloadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setDownloadUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setDownloadUrl(value);
      return this;
    }
    /**
     * <code>optional string downloadUrl = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDownloadUrl() {
      copyOnWrite();
      instance.clearDownloadUrl();
      return this;
    }
    /**
     * <code>optional string downloadUrl = 5;</code>
     * @param value The bytes for downloadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setDownloadUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDownloadUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string compressedDownloadUrl = 6;</code>
     * @return Whether the compressedDownloadUrl field is set.
     */
    @java.lang.Override
    public boolean hasCompressedDownloadUrl() {
      return instance.hasCompressedDownloadUrl();
    }
    /**
     * <code>optional string compressedDownloadUrl = 6;</code>
     * @return The compressedDownloadUrl.
     */
    @java.lang.Override
    public java.lang.String getCompressedDownloadUrl() {
      return instance.getCompressedDownloadUrl();
    }
    /**
     * <code>optional string compressedDownloadUrl = 6;</code>
     * @return The bytes for compressedDownloadUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompressedDownloadUrlBytes() {
      return instance.getCompressedDownloadUrlBytes();
    }
    /**
     * <code>optional string compressedDownloadUrl = 6;</code>
     * @param value The compressedDownloadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setCompressedDownloadUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setCompressedDownloadUrl(value);
      return this;
    }
    /**
     * <code>optional string compressedDownloadUrl = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompressedDownloadUrl() {
      copyOnWrite();
      instance.clearCompressedDownloadUrl();
      return this;
    }
    /**
     * <code>optional string compressedDownloadUrl = 6;</code>
     * @param value The bytes for compressedDownloadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setCompressedDownloadUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCompressedDownloadUrlBytes(value);
      return this;
    }

    /**
     * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
     */
    @java.lang.Override
    public boolean hasPatchData() {
      return instance.hasPatchData();
    }
    /**
     * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
     */
    @java.lang.Override
    public finsky.protos.AndroidAppPatchData getPatchData() {
      return instance.getPatchData();
    }
    /**
     * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
     */
    public Builder setPatchData(finsky.protos.AndroidAppPatchData value) {
      copyOnWrite();
      instance.setPatchData(value);
      return this;
      }
    /**
     * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
     */
    public Builder setPatchData(
        finsky.protos.AndroidAppPatchData.Builder builderForValue) {
      copyOnWrite();
      instance.setPatchData(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
     */
    public Builder mergePatchData(finsky.protos.AndroidAppPatchData value) {
      copyOnWrite();
      instance.mergePatchData(value);
      return this;
    }
    /**
     * <code>optional .finsky.protos.AndroidAppPatchData patchData = 7;</code>
     */
    public Builder clearPatchData() {  copyOnWrite();
      instance.clearPatchData();
      return this;
    }

    /**
     * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
     */
    @java.lang.Override
    public boolean hasCompressedAppData() {
      return instance.hasCompressedAppData();
    }
    /**
     * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
     */
    @java.lang.Override
    public finsky.protos.CompressedAppData getCompressedAppData() {
      return instance.getCompressedAppData();
    }
    /**
     * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
     */
    public Builder setCompressedAppData(finsky.protos.CompressedAppData value) {
      copyOnWrite();
      instance.setCompressedAppData(value);
      return this;
      }
    /**
     * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
     */
    public Builder setCompressedAppData(
        finsky.protos.CompressedAppData.Builder builderForValue) {
      copyOnWrite();
      instance.setCompressedAppData(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
     */
    public Builder mergeCompressedAppData(finsky.protos.CompressedAppData value) {
      copyOnWrite();
      instance.mergeCompressedAppData(value);
      return this;
    }
    /**
     * <code>optional .finsky.protos.CompressedAppData compressedAppData = 8;</code>
     */
    public Builder clearCompressedAppData() {  copyOnWrite();
      instance.clearCompressedAppData();
      return this;
    }

    /**
     * <code>optional string sha256 = 9;</code>
     * @return Whether the sha256 field is set.
     */
    @java.lang.Override
    public boolean hasSha256() {
      return instance.hasSha256();
    }
    /**
     * <code>optional string sha256 = 9;</code>
     * @return The sha256.
     */
    @java.lang.Override
    public java.lang.String getSha256() {
      return instance.getSha256();
    }
    /**
     * <code>optional string sha256 = 9;</code>
     * @return The bytes for sha256.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSha256Bytes() {
      return instance.getSha256Bytes();
    }
    /**
     * <code>optional string sha256 = 9;</code>
     * @param value The sha256 to set.
     * @return This builder for chaining.
     */
    public Builder setSha256(
        java.lang.String value) {
      copyOnWrite();
      instance.setSha256(value);
      return this;
    }
    /**
     * <code>optional string sha256 = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSha256() {
      copyOnWrite();
      instance.clearSha256();
      return this;
    }
    /**
     * <code>optional string sha256 = 9;</code>
     * @param value The bytes for sha256 to set.
     * @return This builder for chaining.
     */
    public Builder setSha256Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSha256Bytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.SplitDeliveryData)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.SplitDeliveryData();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "name_",
            "downloadSize_",
            "compressedSize_",
            "sha1_",
            "downloadUrl_",
            "compressedDownloadUrl_",
            "patchData_",
            "compressedAppData_",
            "sha256_",
          };
          java.lang.String info =
              "\u0001\t\u0000\u0001\u0001\t\t\u0000\u0000\u0000\u0001\u1008\u0000\u0002\u1002\u0001" +
              "\u0003\u1002\u0002\u0004\u1008\u0003\u0005\u1008\u0004\u0006\u1008\u0005\u0007\u1009" +
              "\u0006\b\u1009\u0007\t\u1008\b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.SplitDeliveryData> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.SplitDeliveryData.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.SplitDeliveryData>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.SplitDeliveryData)
  private static final finsky.protos.SplitDeliveryData DEFAULT_INSTANCE;
  static {
    SplitDeliveryData defaultInstance = new SplitDeliveryData();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SplitDeliveryData.class, defaultInstance);
  }

  public static finsky.protos.SplitDeliveryData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SplitDeliveryData> PARSER;

  public static com.google.protobuf.Parser<SplitDeliveryData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

