// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package finsky.protos;

public interface TestingProgramDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.TestingProgramDetails)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bool subscribed = 2;</code>
   * @return Whether the subscribed field is set.
   */
  boolean hasSubscribed();
  /**
   * <code>optional bool subscribed = 2;</code>
   * @return The subscribed.
   */
  boolean getSubscribed();

  /**
   * <code>optional int64 id = 3;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int64 id = 3;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional bool unsubscribed = 4;</code>
   * @return Whether the unsubscribed field is set.
   */
  boolean hasUnsubscribed();
  /**
   * <code>optional bool unsubscribed = 4;</code>
   * @return The unsubscribed.
   */
  boolean getUnsubscribed();
}
