// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.TestingProgramResult}
 */
public  final class TestingProgramResult extends
    com.google.protobuf.GeneratedMessageLite<
        TestingProgramResult, TestingProgramResult.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.TestingProgramResult)
    TestingProgramResultOrBuilder {
  private TestingProgramResult() {
  }
  private int bitField0_;
  public static final int DETAILS_FIELD_NUMBER = 4;
  private finsky.protos.TestingProgramDetails details_;
  /**
   * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
   */
  @java.lang.Override
  public boolean hasDetails() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
   */
  @java.lang.Override
  public finsky.protos.TestingProgramDetails getDetails() {
    return details_ == null ? finsky.protos.TestingProgramDetails.getDefaultInstance() : details_;
  }
  /**
   * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
   */
  private void setDetails(finsky.protos.TestingProgramDetails value) {
    value.getClass();
  details_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDetails(finsky.protos.TestingProgramDetails value) {
    value.getClass();
  if (details_ != null &&
        details_ != finsky.protos.TestingProgramDetails.getDefaultInstance()) {
      details_ =
        finsky.protos.TestingProgramDetails.newBuilder(details_).mergeFrom(value).buildPartial();
    } else {
      details_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
   */
  private void clearDetails() {  details_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static finsky.protos.TestingProgramResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.TestingProgramResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.TestingProgramResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.TestingProgramResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.TestingProgramResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.TestingProgramResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.TestingProgramResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.TestingProgramResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static finsky.protos.TestingProgramResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static finsky.protos.TestingProgramResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.TestingProgramResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.TestingProgramResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.TestingProgramResult prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.TestingProgramResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.TestingProgramResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.TestingProgramResult)
      finsky.protos.TestingProgramResultOrBuilder {
    // Construct using finsky.protos.TestingProgramResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
     */
    @java.lang.Override
    public boolean hasDetails() {
      return instance.hasDetails();
    }
    /**
     * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
     */
    @java.lang.Override
    public finsky.protos.TestingProgramDetails getDetails() {
      return instance.getDetails();
    }
    /**
     * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
     */
    public Builder setDetails(finsky.protos.TestingProgramDetails value) {
      copyOnWrite();
      instance.setDetails(value);
      return this;
      }
    /**
     * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
     */
    public Builder setDetails(
        finsky.protos.TestingProgramDetails.Builder builderForValue) {
      copyOnWrite();
      instance.setDetails(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
     */
    public Builder mergeDetails(finsky.protos.TestingProgramDetails value) {
      copyOnWrite();
      instance.mergeDetails(value);
      return this;
    }
    /**
     * <code>optional .finsky.protos.TestingProgramDetails details = 4;</code>
     */
    public Builder clearDetails() {  copyOnWrite();
      instance.clearDetails();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.TestingProgramResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.TestingProgramResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "details_",
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0001\u0004\u0004\u0001\u0000\u0000\u0000\u0004\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.TestingProgramResult> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.TestingProgramResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.TestingProgramResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.TestingProgramResult)
  private static final finsky.protos.TestingProgramResult DEFAULT_INSTANCE;
  static {
    TestingProgramResult defaultInstance = new TestingProgramResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TestingProgramResult.class, defaultInstance);
  }

  public static finsky.protos.TestingProgramResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TestingProgramResult> PARSER;

  public static com.google.protobuf.Parser<TestingProgramResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

