// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

public interface AndroidEventProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.AndroidEventProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string tag = 1;</code>
   * @return Whether the tag field is set.
   */
  boolean hasTag();
  /**
   * <code>optional string tag = 1;</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>optional string tag = 1;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>optional string value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>optional string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>optional int64 timeMsec = 3;</code>
   * @return Whether the timeMsec field is set.
   */
  boolean hasTimeMsec();
  /**
   * <code>optional int64 timeMsec = 3;</code>
   * @return The timeMsec.
   */
  long getTimeMsec();
}
