// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

public interface DetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:finsky.protos.Details)
    com.google.protobuf.MessageLiteOrBuilder {
}
