// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.EncryptionParams}
 */
public  final class EncryptionParams extends
    com.google.protobuf.GeneratedMessageLite<
        EncryptionParams, EncryptionParams.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.EncryptionParams)
    EncryptionParamsOrBuilder {
  private EncryptionParams() {
    encryptionKey_ = "";
    hMacKey_ = "";
  }
  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>optional int32 version = 1;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }
  /**
   * <code>optional int32 version = 1;</code>
   * @param value The version to set.
   */
  private void setVersion(int value) {
    bitField0_ |= 0x00000001;
    version_ = value;
  }
  /**
   * <code>optional int32 version = 1;</code>
   */
  private void clearVersion() {
    bitField0_ = (bitField0_ & ~0x00000001);
    version_ = 0;
  }

  public static final int ENCRYPTIONKEY_FIELD_NUMBER = 2;
  private java.lang.String encryptionKey_;
  /**
   * <code>optional string encryptionKey = 2;</code>
   * @return Whether the encryptionKey field is set.
   */
  @java.lang.Override
  public boolean hasEncryptionKey() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string encryptionKey = 2;</code>
   * @return The encryptionKey.
   */
  @java.lang.Override
  public java.lang.String getEncryptionKey() {
    return encryptionKey_;
  }
  /**
   * <code>optional string encryptionKey = 2;</code>
   * @return The bytes for encryptionKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEncryptionKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(encryptionKey_);
  }
  /**
   * <code>optional string encryptionKey = 2;</code>
   * @param value The encryptionKey to set.
   */
  private void setEncryptionKey(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
    encryptionKey_ = value;
  }
  /**
   * <code>optional string encryptionKey = 2;</code>
   */
  private void clearEncryptionKey() {
    bitField0_ = (bitField0_ & ~0x00000002);
    encryptionKey_ = getDefaultInstance().getEncryptionKey();
  }
  /**
   * <code>optional string encryptionKey = 2;</code>
   * @param value The bytes for encryptionKey to set.
   */
  private void setEncryptionKeyBytes(
      com.google.protobuf.ByteString value) {
    encryptionKey_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static final int HMACKEY_FIELD_NUMBER = 3;
  private java.lang.String hMacKey_;
  /**
   * <code>optional string hMacKey = 3;</code>
   * @return Whether the hMacKey field is set.
   */
  @java.lang.Override
  public boolean hasHMacKey() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string hMacKey = 3;</code>
   * @return The hMacKey.
   */
  @java.lang.Override
  public java.lang.String getHMacKey() {
    return hMacKey_;
  }
  /**
   * <code>optional string hMacKey = 3;</code>
   * @return The bytes for hMacKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHMacKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(hMacKey_);
  }
  /**
   * <code>optional string hMacKey = 3;</code>
   * @param value The hMacKey to set.
   */
  private void setHMacKey(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
    hMacKey_ = value;
  }
  /**
   * <code>optional string hMacKey = 3;</code>
   */
  private void clearHMacKey() {
    bitField0_ = (bitField0_ & ~0x00000004);
    hMacKey_ = getDefaultInstance().getHMacKey();
  }
  /**
   * <code>optional string hMacKey = 3;</code>
   * @param value The bytes for hMacKey to set.
   */
  private void setHMacKeyBytes(
      com.google.protobuf.ByteString value) {
    hMacKey_ = value.toStringUtf8();
    bitField0_ |= 0x00000004;
  }

  public static finsky.protos.EncryptionParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.EncryptionParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.EncryptionParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.EncryptionParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.EncryptionParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.EncryptionParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.EncryptionParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.EncryptionParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static finsky.protos.EncryptionParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static finsky.protos.EncryptionParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.EncryptionParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.EncryptionParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.EncryptionParams prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.EncryptionParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.EncryptionParams, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.EncryptionParams)
      finsky.protos.EncryptionParamsOrBuilder {
    // Construct using finsky.protos.EncryptionParams.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 version = 1;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return instance.hasVersion();
    }
    /**
     * <code>optional int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>optional int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>optional int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }

    /**
     * <code>optional string encryptionKey = 2;</code>
     * @return Whether the encryptionKey field is set.
     */
    @java.lang.Override
    public boolean hasEncryptionKey() {
      return instance.hasEncryptionKey();
    }
    /**
     * <code>optional string encryptionKey = 2;</code>
     * @return The encryptionKey.
     */
    @java.lang.Override
    public java.lang.String getEncryptionKey() {
      return instance.getEncryptionKey();
    }
    /**
     * <code>optional string encryptionKey = 2;</code>
     * @return The bytes for encryptionKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEncryptionKeyBytes() {
      return instance.getEncryptionKeyBytes();
    }
    /**
     * <code>optional string encryptionKey = 2;</code>
     * @param value The encryptionKey to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptionKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setEncryptionKey(value);
      return this;
    }
    /**
     * <code>optional string encryptionKey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptionKey() {
      copyOnWrite();
      instance.clearEncryptionKey();
      return this;
    }
    /**
     * <code>optional string encryptionKey = 2;</code>
     * @param value The bytes for encryptionKey to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptionKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEncryptionKeyBytes(value);
      return this;
    }

    /**
     * <code>optional string hMacKey = 3;</code>
     * @return Whether the hMacKey field is set.
     */
    @java.lang.Override
    public boolean hasHMacKey() {
      return instance.hasHMacKey();
    }
    /**
     * <code>optional string hMacKey = 3;</code>
     * @return The hMacKey.
     */
    @java.lang.Override
    public java.lang.String getHMacKey() {
      return instance.getHMacKey();
    }
    /**
     * <code>optional string hMacKey = 3;</code>
     * @return The bytes for hMacKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHMacKeyBytes() {
      return instance.getHMacKeyBytes();
    }
    /**
     * <code>optional string hMacKey = 3;</code>
     * @param value The hMacKey to set.
     * @return This builder for chaining.
     */
    public Builder setHMacKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setHMacKey(value);
      return this;
    }
    /**
     * <code>optional string hMacKey = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHMacKey() {
      copyOnWrite();
      instance.clearHMacKey();
      return this;
    }
    /**
     * <code>optional string hMacKey = 3;</code>
     * @param value The bytes for hMacKey to set.
     * @return This builder for chaining.
     */
    public Builder setHMacKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHMacKeyBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:finsky.protos.EncryptionParams)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.EncryptionParams();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "version_",
            "encryptionKey_",
            "hMacKey_",
          };
          java.lang.String info =
              "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1004\u0000\u0002" +
              "\u1008\u0001\u0003\u1008\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.EncryptionParams> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.EncryptionParams.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.EncryptionParams>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.EncryptionParams)
  private static final finsky.protos.EncryptionParams DEFAULT_INSTANCE;
  static {
    EncryptionParams defaultInstance = new EncryptionParams();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EncryptionParams.class, defaultInstance);
  }

  public static finsky.protos.EncryptionParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EncryptionParams> PARSER;

  public static com.google.protobuf.Parser<EncryptionParams> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

