// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.28.2

package finsky.protos;

/**
 * Protobuf type {@code finsky.protos.ResponseMessages}
 */
public  final class ResponseMessages extends
    com.google.protobuf.GeneratedMessageLite<
        ResponseMessages, ResponseMessages.Builder> implements
    // @@protoc_insertion_point(message_implements:finsky.protos.ResponseMessages)
    ResponseMessagesOrBuilder {
  private ResponseMessages() {
  }
  public interface ServerCommandsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:finsky.protos.ResponseMessages.ServerCommands)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bool clearCache = 1;</code>
     * @return Whether the clearCache field is set.
     */
    boolean hasClearCache();
    /**
     * <code>optional bool clearCache = 1;</code>
     * @return The clearCache.
     */
    boolean getClearCache();

    /**
     * <code>optional string displayErrorMessage = 2;</code>
     * @return Whether the displayErrorMessage field is set.
     */
    boolean hasDisplayErrorMessage();
    /**
     * <code>optional string displayErrorMessage = 2;</code>
     * @return The displayErrorMessage.
     */
    java.lang.String getDisplayErrorMessage();
    /**
     * <code>optional string displayErrorMessage = 2;</code>
     * @return The bytes for displayErrorMessage.
     */
    com.google.protobuf.ByteString
        getDisplayErrorMessageBytes();

    /**
     * <code>optional string logErrorStacktrace = 3;</code>
     * @return Whether the logErrorStacktrace field is set.
     */
    boolean hasLogErrorStacktrace();
    /**
     * <code>optional string logErrorStacktrace = 3;</code>
     * @return The logErrorStacktrace.
     */
    java.lang.String getLogErrorStacktrace();
    /**
     * <code>optional string logErrorStacktrace = 3;</code>
     * @return The bytes for logErrorStacktrace.
     */
    com.google.protobuf.ByteString
        getLogErrorStacktraceBytes();
  }
  /**
   * Protobuf type {@code finsky.protos.ResponseMessages.ServerCommands}
   */
  public  static final class ServerCommands extends
      com.google.protobuf.GeneratedMessageLite<
          ServerCommands, ServerCommands.Builder> implements
      // @@protoc_insertion_point(message_implements:finsky.protos.ResponseMessages.ServerCommands)
      ServerCommandsOrBuilder {
    private ServerCommands() {
      displayErrorMessage_ = "";
      logErrorStacktrace_ = "";
    }
    private int bitField0_;
    public static final int CLEARCACHE_FIELD_NUMBER = 1;
    private boolean clearCache_;
    /**
     * <code>optional bool clearCache = 1;</code>
     * @return Whether the clearCache field is set.
     */
    @java.lang.Override
    public boolean hasClearCache() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool clearCache = 1;</code>
     * @return The clearCache.
     */
    @java.lang.Override
    public boolean getClearCache() {
      return clearCache_;
    }
    /**
     * <code>optional bool clearCache = 1;</code>
     * @param value The clearCache to set.
     */
    private void setClearCache(boolean value) {
      bitField0_ |= 0x00000001;
      clearCache_ = value;
    }
    /**
     * <code>optional bool clearCache = 1;</code>
     */
    private void clearClearCache() {
      bitField0_ = (bitField0_ & ~0x00000001);
      clearCache_ = false;
    }

    public static final int DISPLAYERRORMESSAGE_FIELD_NUMBER = 2;
    private java.lang.String displayErrorMessage_;
    /**
     * <code>optional string displayErrorMessage = 2;</code>
     * @return Whether the displayErrorMessage field is set.
     */
    @java.lang.Override
    public boolean hasDisplayErrorMessage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string displayErrorMessage = 2;</code>
     * @return The displayErrorMessage.
     */
    @java.lang.Override
    public java.lang.String getDisplayErrorMessage() {
      return displayErrorMessage_;
    }
    /**
     * <code>optional string displayErrorMessage = 2;</code>
     * @return The bytes for displayErrorMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisplayErrorMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(displayErrorMessage_);
    }
    /**
     * <code>optional string displayErrorMessage = 2;</code>
     * @param value The displayErrorMessage to set.
     */
    private void setDisplayErrorMessage(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      displayErrorMessage_ = value;
    }
    /**
     * <code>optional string displayErrorMessage = 2;</code>
     */
    private void clearDisplayErrorMessage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      displayErrorMessage_ = getDefaultInstance().getDisplayErrorMessage();
    }
    /**
     * <code>optional string displayErrorMessage = 2;</code>
     * @param value The bytes for displayErrorMessage to set.
     */
    private void setDisplayErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      displayErrorMessage_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int LOGERRORSTACKTRACE_FIELD_NUMBER = 3;
    private java.lang.String logErrorStacktrace_;
    /**
     * <code>optional string logErrorStacktrace = 3;</code>
     * @return Whether the logErrorStacktrace field is set.
     */
    @java.lang.Override
    public boolean hasLogErrorStacktrace() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string logErrorStacktrace = 3;</code>
     * @return The logErrorStacktrace.
     */
    @java.lang.Override
    public java.lang.String getLogErrorStacktrace() {
      return logErrorStacktrace_;
    }
    /**
     * <code>optional string logErrorStacktrace = 3;</code>
     * @return The bytes for logErrorStacktrace.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogErrorStacktraceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(logErrorStacktrace_);
    }
    /**
     * <code>optional string logErrorStacktrace = 3;</code>
     * @param value The logErrorStacktrace to set.
     */
    private void setLogErrorStacktrace(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
      logErrorStacktrace_ = value;
    }
    /**
     * <code>optional string logErrorStacktrace = 3;</code>
     */
    private void clearLogErrorStacktrace() {
      bitField0_ = (bitField0_ & ~0x00000004);
      logErrorStacktrace_ = getDefaultInstance().getLogErrorStacktrace();
    }
    /**
     * <code>optional string logErrorStacktrace = 3;</code>
     * @param value The bytes for logErrorStacktrace to set.
     */
    private void setLogErrorStacktraceBytes(
        com.google.protobuf.ByteString value) {
      logErrorStacktrace_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static finsky.protos.ResponseMessages.ServerCommands parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static finsky.protos.ResponseMessages.ServerCommands parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static finsky.protos.ResponseMessages.ServerCommands parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(finsky.protos.ResponseMessages.ServerCommands prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code finsky.protos.ResponseMessages.ServerCommands}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          finsky.protos.ResponseMessages.ServerCommands, Builder> implements
        // @@protoc_insertion_point(builder_implements:finsky.protos.ResponseMessages.ServerCommands)
        finsky.protos.ResponseMessages.ServerCommandsOrBuilder {
      // Construct using finsky.protos.ResponseMessages.ServerCommands.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional bool clearCache = 1;</code>
       * @return Whether the clearCache field is set.
       */
      @java.lang.Override
      public boolean hasClearCache() {
        return instance.hasClearCache();
      }
      /**
       * <code>optional bool clearCache = 1;</code>
       * @return The clearCache.
       */
      @java.lang.Override
      public boolean getClearCache() {
        return instance.getClearCache();
      }
      /**
       * <code>optional bool clearCache = 1;</code>
       * @param value The clearCache to set.
       * @return This builder for chaining.
       */
      public Builder setClearCache(boolean value) {
        copyOnWrite();
        instance.setClearCache(value);
        return this;
      }
      /**
       * <code>optional bool clearCache = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClearCache() {
        copyOnWrite();
        instance.clearClearCache();
        return this;
      }

      /**
       * <code>optional string displayErrorMessage = 2;</code>
       * @return Whether the displayErrorMessage field is set.
       */
      @java.lang.Override
      public boolean hasDisplayErrorMessage() {
        return instance.hasDisplayErrorMessage();
      }
      /**
       * <code>optional string displayErrorMessage = 2;</code>
       * @return The displayErrorMessage.
       */
      @java.lang.Override
      public java.lang.String getDisplayErrorMessage() {
        return instance.getDisplayErrorMessage();
      }
      /**
       * <code>optional string displayErrorMessage = 2;</code>
       * @return The bytes for displayErrorMessage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDisplayErrorMessageBytes() {
        return instance.getDisplayErrorMessageBytes();
      }
      /**
       * <code>optional string displayErrorMessage = 2;</code>
       * @param value The displayErrorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setDisplayErrorMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setDisplayErrorMessage(value);
        return this;
      }
      /**
       * <code>optional string displayErrorMessage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDisplayErrorMessage() {
        copyOnWrite();
        instance.clearDisplayErrorMessage();
        return this;
      }
      /**
       * <code>optional string displayErrorMessage = 2;</code>
       * @param value The bytes for displayErrorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setDisplayErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDisplayErrorMessageBytes(value);
        return this;
      }

      /**
       * <code>optional string logErrorStacktrace = 3;</code>
       * @return Whether the logErrorStacktrace field is set.
       */
      @java.lang.Override
      public boolean hasLogErrorStacktrace() {
        return instance.hasLogErrorStacktrace();
      }
      /**
       * <code>optional string logErrorStacktrace = 3;</code>
       * @return The logErrorStacktrace.
       */
      @java.lang.Override
      public java.lang.String getLogErrorStacktrace() {
        return instance.getLogErrorStacktrace();
      }
      /**
       * <code>optional string logErrorStacktrace = 3;</code>
       * @return The bytes for logErrorStacktrace.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLogErrorStacktraceBytes() {
        return instance.getLogErrorStacktraceBytes();
      }
      /**
       * <code>optional string logErrorStacktrace = 3;</code>
       * @param value The logErrorStacktrace to set.
       * @return This builder for chaining.
       */
      public Builder setLogErrorStacktrace(
          java.lang.String value) {
        copyOnWrite();
        instance.setLogErrorStacktrace(value);
        return this;
      }
      /**
       * <code>optional string logErrorStacktrace = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogErrorStacktrace() {
        copyOnWrite();
        instance.clearLogErrorStacktrace();
        return this;
      }
      /**
       * <code>optional string logErrorStacktrace = 3;</code>
       * @param value The bytes for logErrorStacktrace to set.
       * @return This builder for chaining.
       */
      public Builder setLogErrorStacktraceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLogErrorStacktraceBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:finsky.protos.ResponseMessages.ServerCommands)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new finsky.protos.ResponseMessages.ServerCommands();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "clearCache_",
              "displayErrorMessage_",
              "logErrorStacktrace_",
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1007\u0000\u0002" +
                "\u1008\u0001\u0003\u1008\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<finsky.protos.ResponseMessages.ServerCommands> parser = PARSER;
          if (parser == null) {
            synchronized (finsky.protos.ResponseMessages.ServerCommands.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<finsky.protos.ResponseMessages.ServerCommands>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:finsky.protos.ResponseMessages.ServerCommands)
    private static final finsky.protos.ResponseMessages.ServerCommands DEFAULT_INSTANCE;
    static {
      ServerCommands defaultInstance = new ServerCommands();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ServerCommands.class, defaultInstance);
    }

    public static finsky.protos.ResponseMessages.ServerCommands getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ServerCommands> PARSER;

    public static com.google.protobuf.Parser<ServerCommands> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ServerMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:finsky.protos.ResponseMessages.ServerMetadata)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int64 latencyMillis = 1;</code>
     * @return Whether the latencyMillis field is set.
     */
    boolean hasLatencyMillis();
    /**
     * <code>optional int64 latencyMillis = 1;</code>
     * @return The latencyMillis.
     */
    long getLatencyMillis();
  }
  /**
   * Protobuf type {@code finsky.protos.ResponseMessages.ServerMetadata}
   */
  public  static final class ServerMetadata extends
      com.google.protobuf.GeneratedMessageLite<
          ServerMetadata, ServerMetadata.Builder> implements
      // @@protoc_insertion_point(message_implements:finsky.protos.ResponseMessages.ServerMetadata)
      ServerMetadataOrBuilder {
    private ServerMetadata() {
    }
    private int bitField0_;
    public static final int LATENCYMILLIS_FIELD_NUMBER = 1;
    private long latencyMillis_;
    /**
     * <code>optional int64 latencyMillis = 1;</code>
     * @return Whether the latencyMillis field is set.
     */
    @java.lang.Override
    public boolean hasLatencyMillis() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 latencyMillis = 1;</code>
     * @return The latencyMillis.
     */
    @java.lang.Override
    public long getLatencyMillis() {
      return latencyMillis_;
    }
    /**
     * <code>optional int64 latencyMillis = 1;</code>
     * @param value The latencyMillis to set.
     */
    private void setLatencyMillis(long value) {
      bitField0_ |= 0x00000001;
      latencyMillis_ = value;
    }
    /**
     * <code>optional int64 latencyMillis = 1;</code>
     */
    private void clearLatencyMillis() {
      bitField0_ = (bitField0_ & ~0x00000001);
      latencyMillis_ = 0L;
    }

    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static finsky.protos.ResponseMessages.ServerMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static finsky.protos.ResponseMessages.ServerMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static finsky.protos.ResponseMessages.ServerMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(finsky.protos.ResponseMessages.ServerMetadata prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code finsky.protos.ResponseMessages.ServerMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          finsky.protos.ResponseMessages.ServerMetadata, Builder> implements
        // @@protoc_insertion_point(builder_implements:finsky.protos.ResponseMessages.ServerMetadata)
        finsky.protos.ResponseMessages.ServerMetadataOrBuilder {
      // Construct using finsky.protos.ResponseMessages.ServerMetadata.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int64 latencyMillis = 1;</code>
       * @return Whether the latencyMillis field is set.
       */
      @java.lang.Override
      public boolean hasLatencyMillis() {
        return instance.hasLatencyMillis();
      }
      /**
       * <code>optional int64 latencyMillis = 1;</code>
       * @return The latencyMillis.
       */
      @java.lang.Override
      public long getLatencyMillis() {
        return instance.getLatencyMillis();
      }
      /**
       * <code>optional int64 latencyMillis = 1;</code>
       * @param value The latencyMillis to set.
       * @return This builder for chaining.
       */
      public Builder setLatencyMillis(long value) {
        copyOnWrite();
        instance.setLatencyMillis(value);
        return this;
      }
      /**
       * <code>optional int64 latencyMillis = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatencyMillis() {
        copyOnWrite();
        instance.clearLatencyMillis();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:finsky.protos.ResponseMessages.ServerMetadata)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new finsky.protos.ResponseMessages.ServerMetadata();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "latencyMillis_",
            };
            java.lang.String info =
                "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1002\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<finsky.protos.ResponseMessages.ServerMetadata> parser = PARSER;
          if (parser == null) {
            synchronized (finsky.protos.ResponseMessages.ServerMetadata.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<finsky.protos.ResponseMessages.ServerMetadata>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:finsky.protos.ResponseMessages.ServerMetadata)
    private static final finsky.protos.ResponseMessages.ServerMetadata DEFAULT_INSTANCE;
    static {
      ServerMetadata defaultInstance = new ServerMetadata();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ServerMetadata.class, defaultInstance);
    }

    public static finsky.protos.ResponseMessages.ServerMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ServerMetadata> PARSER;

    public static com.google.protobuf.Parser<ServerMetadata> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static finsky.protos.ResponseMessages parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.ResponseMessages parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.ResponseMessages parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.ResponseMessages parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.ResponseMessages parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static finsky.protos.ResponseMessages parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static finsky.protos.ResponseMessages parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.ResponseMessages parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static finsky.protos.ResponseMessages parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static finsky.protos.ResponseMessages parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static finsky.protos.ResponseMessages parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static finsky.protos.ResponseMessages parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(finsky.protos.ResponseMessages prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code finsky.protos.ResponseMessages}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        finsky.protos.ResponseMessages, Builder> implements
      // @@protoc_insertion_point(builder_implements:finsky.protos.ResponseMessages)
      finsky.protos.ResponseMessagesOrBuilder {
    // Construct using finsky.protos.ResponseMessages.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    // @@protoc_insertion_point(builder_scope:finsky.protos.ResponseMessages)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new finsky.protos.ResponseMessages();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = null;java.lang.String info =
              "\u0001\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<finsky.protos.ResponseMessages> parser = PARSER;
        if (parser == null) {
          synchronized (finsky.protos.ResponseMessages.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<finsky.protos.ResponseMessages>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:finsky.protos.ResponseMessages)
  private static final finsky.protos.ResponseMessages DEFAULT_INSTANCE;
  static {
    ResponseMessages defaultInstance = new ResponseMessages();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ResponseMessages.class, defaultInstance);
  }

  public static finsky.protos.ResponseMessages getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ResponseMessages> PARSER;

  public static com.google.protobuf.Parser<ResponseMessages> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

